# CMake generated Testfile for 
# Source directory: /home/pi/sdk-folder/sdk-source/avs-device-sdk/capabilities/AudioPlayer/acsdkAudioPlayer/test
# Build directory: /home/pi/sdk-folder/sdk-build/EXTENSION/AudioPlayer/acsdkAudioPlayer/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(AudioPlayerTest.test_createWithNullPointers "/home/pi/sdk-folder/sdk-build/EXTENSION/AudioPlayer/acsdkAudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.test_createWithNullPointers")
add_test(AudioPlayerTest.test_transitionFromIdleToPlaying "/home/pi/sdk-folder/sdk-build/EXTENSION/AudioPlayer/acsdkAudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.test_transitionFromIdleToPlaying")
add_test(AudioPlayerTest.test_transitionFromPlayingToStopped "/home/pi/sdk-folder/sdk-build/EXTENSION/AudioPlayer/acsdkAudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.test_transitionFromPlayingToStopped")
add_test(AudioPlayerTest.test_transitionFromPlayingToStoppedToIdleWithClearAll "/home/pi/sdk-folder/sdk-build/EXTENSION/AudioPlayer/acsdkAudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.test_transitionFromPlayingToStoppedToIdleWithClearAll")
add_test(AudioPlayerTest.test_continuesPlayingWithClearEnqueued "/home/pi/sdk-folder/sdk-build/EXTENSION/AudioPlayer/acsdkAudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.test_continuesPlayingWithClearEnqueued")
add_test(AudioPlayerTest.test_transitionFromIdleToPlayingAfterClearAll "/home/pi/sdk-folder/sdk-build/EXTENSION/AudioPlayer/acsdkAudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.test_transitionFromIdleToPlayingAfterClearAll")
add_test(AudioPlayerTest.testTransitionFromIdleToResumePlaying "/home/pi/sdk-folder/sdk-build/EXTENSION/AudioPlayer/acsdkAudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.testTransitionFromIdleToResumePlaying")
add_test(AudioPlayerTest.testTransitionFromPlayingToPlayingNextEnqueuedTrack "/home/pi/sdk-folder/sdk-build/EXTENSION/AudioPlayer/acsdkAudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.testTransitionFromPlayingToPlayingNextEnqueuedTrack")
add_test(AudioPlayerTest.test_transitionFromPlayingToPaused "/home/pi/sdk-folder/sdk-build/EXTENSION/AudioPlayer/acsdkAudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.test_transitionFromPlayingToPaused")
add_test(AudioPlayerTest.test_localPause_withEnqueuedTracks_doesNotAutoProgress "/home/pi/sdk-folder/sdk-build/EXTENSION/AudioPlayer/acsdkAudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.test_localPause_withEnqueuedTracks_doesNotAutoProgress")
add_test(AudioPlayerTest.test_transitionFromPausedToStopped "/home/pi/sdk-folder/sdk-build/EXTENSION/AudioPlayer/acsdkAudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.test_transitionFromPausedToStopped")
add_test(AudioPlayerTest.test_transitionFromPausedToIdle "/home/pi/sdk-folder/sdk-build/EXTENSION/AudioPlayer/acsdkAudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.test_transitionFromPausedToIdle")
add_test(AudioPlayerTest.test_resumeAfterPaused "/home/pi/sdk-folder/sdk-build/EXTENSION/AudioPlayer/acsdkAudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.test_resumeAfterPaused")
add_test(AudioPlayerTest.test_callingProvideStateWhenIdle "/home/pi/sdk-folder/sdk-build/EXTENSION/AudioPlayer/acsdkAudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.test_callingProvideStateWhenIdle")
add_test(AudioPlayerTest.test_onPlaybackError "/home/pi/sdk-folder/sdk-build/EXTENSION/AudioPlayer/acsdkAudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.test_onPlaybackError")
add_test(AudioPlayerTest.test_onPlaybackError_Stopped "/home/pi/sdk-folder/sdk-build/EXTENSION/AudioPlayer/acsdkAudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.test_onPlaybackError_Stopped")
add_test(AudioPlayerTest.testPrebufferOnPlaybackError "/home/pi/sdk-folder/sdk-build/EXTENSION/AudioPlayer/acsdkAudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.testPrebufferOnPlaybackError")
add_test(AudioPlayerTest.test_onPlaybackPaused "/home/pi/sdk-folder/sdk-build/EXTENSION/AudioPlayer/acsdkAudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.test_onPlaybackPaused")
add_test(AudioPlayerTest.test_onPlaybackResumed "/home/pi/sdk-folder/sdk-build/EXTENSION/AudioPlayer/acsdkAudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.test_onPlaybackResumed")
add_test(AudioPlayerTest.test_onPlaybackFinished_bufferCompleteAfterStarted "/home/pi/sdk-folder/sdk-build/EXTENSION/AudioPlayer/acsdkAudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.test_onPlaybackFinished_bufferCompleteAfterStarted")
add_test(AudioPlayerTest.test_onPlaybackFinished_bufferCompleteBeforeStarted "/home/pi/sdk-folder/sdk-build/EXTENSION/AudioPlayer/acsdkAudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.test_onPlaybackFinished_bufferCompleteBeforeStarted")
add_test(AudioPlayerTest.testOnPlaybackFinishedWithPlaybackAttributes "/home/pi/sdk-folder/sdk-build/EXTENSION/AudioPlayer/acsdkAudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.testOnPlaybackFinishedWithPlaybackAttributes")
add_test(AudioPlayerTest.testOnPlaybackStoppedWithPlaybackReports "/home/pi/sdk-folder/sdk-build/EXTENSION/AudioPlayer/acsdkAudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.testOnPlaybackStoppedWithPlaybackReports")
add_test(AudioPlayerTest.test_onBufferUnderrun "/home/pi/sdk-folder/sdk-build/EXTENSION/AudioPlayer/acsdkAudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.test_onBufferUnderrun")
add_test(AudioPlayerTest.testTimer_onBufferRefilled "/home/pi/sdk-folder/sdk-build/EXTENSION/AudioPlayer/acsdkAudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.testTimer_onBufferRefilled")
set_tests_properties(AudioPlayerTest.testTimer_onBufferRefilled PROPERTIES  LABELS "timertest")
add_test(AudioPlayerTest.test_onTags_filteredOut "/home/pi/sdk-folder/sdk-build/EXTENSION/AudioPlayer/acsdkAudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.test_onTags_filteredOut")
add_test(AudioPlayerTest.test_onTags_filteredIn "/home/pi/sdk-folder/sdk-build/EXTENSION/AudioPlayer/acsdkAudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.test_onTags_filteredIn")
add_test(AudioPlayerTest.test_onTags_filteredIn_rateCheck "/home/pi/sdk-folder/sdk-build/EXTENSION/AudioPlayer/acsdkAudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.test_onTags_filteredIn_rateCheck")
add_test(AudioPlayerTest.test_onTags_filteredIn_duplicateCheck "/home/pi/sdk-folder/sdk-build/EXTENSION/AudioPlayer/acsdkAudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.test_onTags_filteredIn_duplicateCheck")
add_test(AudioPlayerTest.test_cancelDirective "/home/pi/sdk-folder/sdk-build/EXTENSION/AudioPlayer/acsdkAudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.test_cancelDirective")
add_test(AudioPlayerTest.test_focusChangeToNoneInIdleState "/home/pi/sdk-folder/sdk-build/EXTENSION/AudioPlayer/acsdkAudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.test_focusChangeToNoneInIdleState")
add_test(AudioPlayerTest.test_focusChangeFromForegroundToBackgroundInIdleState "/home/pi/sdk-folder/sdk-build/EXTENSION/AudioPlayer/acsdkAudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.test_focusChangeFromForegroundToBackgroundInIdleState")
add_test(AudioPlayerTest.test_focusChangeFromNoneToBackgroundInIdleState "/home/pi/sdk-folder/sdk-build/EXTENSION/AudioPlayer/acsdkAudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.test_focusChangeFromNoneToBackgroundInIdleState")
add_test(AudioPlayerTest.test_focusChangesInPlayingState "/home/pi/sdk-folder/sdk-build/EXTENSION/AudioPlayer/acsdkAudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.test_focusChangesInPlayingState")
add_test(AudioPlayerTest.test_focusChangesInStoppedState "/home/pi/sdk-folder/sdk-build/EXTENSION/AudioPlayer/acsdkAudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.test_focusChangesInStoppedState")
add_test(AudioPlayerTest.test_focusChangesInPausedState "/home/pi/sdk-folder/sdk-build/EXTENSION/AudioPlayer/acsdkAudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.test_focusChangesInPausedState")
add_test(AudioPlayerTest.test_focusChangesInBufferUnderrunState "/home/pi/sdk-folder/sdk-build/EXTENSION/AudioPlayer/acsdkAudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.test_focusChangesInBufferUnderrunState")
add_test(AudioPlayerTest.test_focusChangeToBackgroundBeforeOnPlaybackStarted "/home/pi/sdk-folder/sdk-build/EXTENSION/AudioPlayer/acsdkAudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.test_focusChangeToBackgroundBeforeOnPlaybackStarted")
add_test(AudioPlayerTest.test_playAfterOnPlaybackError "/home/pi/sdk-folder/sdk-build/EXTENSION/AudioPlayer/acsdkAudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.test_playAfterOnPlaybackError")
add_test(AudioPlayerTest.test_playCallsCaptionManager "/home/pi/sdk-folder/sdk-build/EXTENSION/AudioPlayer/acsdkAudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.test_playCallsCaptionManager")
add_test(AudioPlayerTest.test_playParsesCaptionPayload "/home/pi/sdk-folder/sdk-build/EXTENSION/AudioPlayer/acsdkAudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.test_playParsesCaptionPayload")
add_test(AudioPlayerTest.test_playbackStartedSwitchesHandler "/home/pi/sdk-folder/sdk-build/EXTENSION/AudioPlayer/acsdkAudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.test_playbackStartedSwitchesHandler")
add_test(AudioPlayerTest.test_progressReportDelayElapsed "/home/pi/sdk-folder/sdk-build/EXTENSION/AudioPlayer/acsdkAudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.test_progressReportDelayElapsed")
add_test(AudioPlayerTest.test_progressReportDelayElapsedDelayLessThanOffset "/home/pi/sdk-folder/sdk-build/EXTENSION/AudioPlayer/acsdkAudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.test_progressReportDelayElapsedDelayLessThanOffset")
add_test(AudioPlayerTest.testTimer_progressReportIntervalElapsed "/home/pi/sdk-folder/sdk-build/EXTENSION/AudioPlayer/acsdkAudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.testTimer_progressReportIntervalElapsed")
set_tests_properties(AudioPlayerTest.testTimer_progressReportIntervalElapsed PROPERTIES  LABELS "timertest")
add_test(AudioPlayerTest.test_progressReportIntervalElapsedIntervalLessThanOffset "/home/pi/sdk-folder/sdk-build/EXTENSION/AudioPlayer/acsdkAudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.test_progressReportIntervalElapsedIntervalLessThanOffset")
add_test(AudioPlayerTest.testSlow_playOnlyAfterForegroundFocus "/home/pi/sdk-folder/sdk-build/EXTENSION/AudioPlayer/acsdkAudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.testSlow_playOnlyAfterForegroundFocus")
set_tests_properties(AudioPlayerTest.testSlow_playOnlyAfterForegroundFocus PROPERTIES  LABELS "slowtest")
add_test(AudioPlayerTest.testSlow_focusChangeRaceOnPlay "/home/pi/sdk-folder/sdk-build/EXTENSION/AudioPlayer/acsdkAudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.testSlow_focusChangeRaceOnPlay")
set_tests_properties(AudioPlayerTest.testSlow_focusChangeRaceOnPlay PROPERTIES  LABELS "slowtest")
add_test(AudioPlayerTest.testTimer_playbackStartedCallbackAfterFocusLost "/home/pi/sdk-folder/sdk-build/EXTENSION/AudioPlayer/acsdkAudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.testTimer_playbackStartedCallbackAfterFocusLost")
set_tests_properties(AudioPlayerTest.testTimer_playbackStartedCallbackAfterFocusLost PROPERTIES  LABELS "timertest")
add_test(AudioPlayerTest.test1PlayerPool_PlayEnqueueFinishPlay "/home/pi/sdk-folder/sdk-build/EXTENSION/AudioPlayer/acsdkAudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.test1PlayerPool_PlayEnqueueFinishPlay")
add_test(AudioPlayerTest.test2PlayerPool_PlayEnqueueFinishPlay "/home/pi/sdk-folder/sdk-build/EXTENSION/AudioPlayer/acsdkAudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.test2PlayerPool_PlayEnqueueFinishPlay")
add_test(AudioPlayerTest.test3PlayerPool_PlayEnqueueFinishPlay "/home/pi/sdk-folder/sdk-build/EXTENSION/AudioPlayer/acsdkAudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.test3PlayerPool_PlayEnqueueFinishPlay")
add_test(AudioPlayerTest.testPlayRequestor "/home/pi/sdk-folder/sdk-build/EXTENSION/AudioPlayer/acsdkAudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.testPlayRequestor")
add_test(AudioPlayerTest.testUpdateProgressReportInterval "/home/pi/sdk-folder/sdk-build/EXTENSION/AudioPlayer/acsdkAudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.testUpdateProgressReportInterval")
add_test(AudioPlayerTest.testTimer_playbackFinishedMessageOrder_1Player "/home/pi/sdk-folder/sdk-build/EXTENSION/AudioPlayer/acsdkAudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.testTimer_playbackFinishedMessageOrder_1Player")
set_tests_properties(AudioPlayerTest.testTimer_playbackFinishedMessageOrder_1Player PROPERTIES  LABELS "timertest")
add_test(AudioPlayerTest.testTimer_playbackFinishedMessageOrder_2Players "/home/pi/sdk-folder/sdk-build/EXTENSION/AudioPlayer/acsdkAudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.testTimer_playbackFinishedMessageOrder_2Players")
set_tests_properties(AudioPlayerTest.testTimer_playbackFinishedMessageOrder_2Players PROPERTIES  LABELS "timertest")
add_test(AudioPlayerTest.testTimer_playbackStoppedMessageOrder_1Player "/home/pi/sdk-folder/sdk-build/EXTENSION/AudioPlayer/acsdkAudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.testTimer_playbackStoppedMessageOrder_1Player")
set_tests_properties(AudioPlayerTest.testTimer_playbackStoppedMessageOrder_1Player PROPERTIES  LABELS "timertest")
add_test(AudioPlayerTest.testTimer_playbackStoppedMessageOrder_2Players "/home/pi/sdk-folder/sdk-build/EXTENSION/AudioPlayer/acsdkAudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.testTimer_playbackStoppedMessageOrder_2Players")
set_tests_properties(AudioPlayerTest.testTimer_playbackStoppedMessageOrder_2Players PROPERTIES  LABELS "timertest")
add_test(AudioPlayerTest.test_publishedCapabiltiesContainsFingerprint "/home/pi/sdk-folder/sdk-build/EXTENSION/AudioPlayer/acsdkAudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.test_publishedCapabiltiesContainsFingerprint")
add_test(AudioPlayerTest.test_localStop "/home/pi/sdk-folder/sdk-build/EXTENSION/AudioPlayer/acsdkAudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.test_localStop")
add_test(AudioPlayerTest.test_localPause "/home/pi/sdk-folder/sdk-build/EXTENSION/AudioPlayer/acsdkAudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.test_localPause")
add_test(AudioPlayerTest.test_localResumeAfterPaused "/home/pi/sdk-folder/sdk-build/EXTENSION/AudioPlayer/acsdkAudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.test_localResumeAfterPaused")
add_test(AudioPlayerTest.test_localSeekTo "/home/pi/sdk-folder/sdk-build/EXTENSION/AudioPlayer/acsdkAudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.test_localSeekTo")
add_test(AudioPlayerTest.test_localSeekToWhileLocalStopped "/home/pi/sdk-folder/sdk-build/EXTENSION/AudioPlayer/acsdkAudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.test_localSeekToWhileLocalStopped")
add_test(AudioPlayerTest.test_endOffset "/home/pi/sdk-folder/sdk-build/EXTENSION/AudioPlayer/acsdkAudioPlayer/test/AudioPlayerTest" "--gtest_also_run_disabled_tests" "--gtest_filter=AudioPlayerTest.DISABLED_test_endOffset")
set_tests_properties(AudioPlayerTest.test_endOffset PROPERTIES  DISABLED "TRUE")
add_test(AudioPlayerTest.test_badEndOffset "/home/pi/sdk-folder/sdk-build/EXTENSION/AudioPlayer/acsdkAudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.test_badEndOffset")
add_test(AudioPlayerTest.test_badEndOffsetEqualValue "/home/pi/sdk-folder/sdk-build/EXTENSION/AudioPlayer/acsdkAudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.test_badEndOffsetEqualValue")
add_test(ProgressTimerTest.test_noDelayOrInterval "/home/pi/sdk-folder/sdk-build/EXTENSION/AudioPlayer/acsdkAudioPlayer/test/ProgressTimerTest" "--gtest_filter=ProgressTimerTest.test_noDelayOrInterval")
add_test(ProgressTimerTest.test_zeroInterval "/home/pi/sdk-folder/sdk-build/EXTENSION/AudioPlayer/acsdkAudioPlayer/test/ProgressTimerTest" "--gtest_filter=ProgressTimerTest.test_zeroInterval")
add_test(ProgressTimerTest.test_justDelay "/home/pi/sdk-folder/sdk-build/EXTENSION/AudioPlayer/acsdkAudioPlayer/test/ProgressTimerTest" "--gtest_filter=ProgressTimerTest.test_justDelay")
add_test(ProgressTimerTest.test_justInterval "/home/pi/sdk-folder/sdk-build/EXTENSION/AudioPlayer/acsdkAudioPlayer/test/ProgressTimerTest" "--gtest_filter=ProgressTimerTest.test_justInterval")
add_test(ProgressTimerTest.test_delayAndInterval "/home/pi/sdk-folder/sdk-build/EXTENSION/AudioPlayer/acsdkAudioPlayer/test/ProgressTimerTest" "--gtest_filter=ProgressTimerTest.test_delayAndInterval")
add_test(ProgressTimerTest.test_pause "/home/pi/sdk-folder/sdk-build/EXTENSION/AudioPlayer/acsdkAudioPlayer/test/ProgressTimerTest" "--gtest_filter=ProgressTimerTest.test_pause")
add_test(ProgressTimerTest.test_resumeDoesNotRepeat "/home/pi/sdk-folder/sdk-build/EXTENSION/AudioPlayer/acsdkAudioPlayer/test/ProgressTimerTest" "--gtest_filter=ProgressTimerTest.test_resumeDoesNotRepeat")
add_test(ProgressTimerTest.testTimer_offsets "/home/pi/sdk-folder/sdk-build/EXTENSION/AudioPlayer/acsdkAudioPlayer/test/ProgressTimerTest" "--gtest_filter=ProgressTimerTest.testTimer_offsets")
set_tests_properties(ProgressTimerTest.testTimer_offsets PROPERTIES  LABELS "timertest")
add_test(ProgressTimerTest.test_delayAndIntervalCoincide "/home/pi/sdk-folder/sdk-build/EXTENSION/AudioPlayer/acsdkAudioPlayer/test/ProgressTimerTest" "--gtest_filter=ProgressTimerTest.test_delayAndIntervalCoincide")
add_test(ProgressTimerTest.test_updateInterval "/home/pi/sdk-folder/sdk-build/EXTENSION/AudioPlayer/acsdkAudioPlayer/test/ProgressTimerTest" "--gtest_filter=ProgressTimerTest.test_updateInterval")
add_test(ProgressTimerTest.test_updateIntervalAfterStop "/home/pi/sdk-folder/sdk-build/EXTENSION/AudioPlayer/acsdkAudioPlayer/test/ProgressTimerTest" "--gtest_filter=ProgressTimerTest.test_updateIntervalAfterStop")
