# CMake generated Testfile for 
# Source directory: /home/pi/sdk-folder/sdk-source/avs-device-sdk/AVSCommon/Utils/test
# Build directory: /home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(PlaybackContextTest.test_validateHeadersWithEmptyAndValidData "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/PlaybackContextTest" "--gtest_filter=PlaybackContextTest.test_validateHeadersWithEmptyAndValidData")
add_test(PlaybackContextTest.test_validateMixValidInvalidHeaders "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/PlaybackContextTest" "--gtest_filter=PlaybackContextTest.test_validateMixValidInvalidHeaders")
add_test(PlaybackContextTest.test_validateHeadersWithMaxValueSize "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/PlaybackContextTest" "--gtest_filter=PlaybackContextTest.test_validateHeadersWithMaxValueSize")
add_test(PlaybackContextTest.test_headersWithMaxKeySize "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/PlaybackContextTest" "--gtest_filter=PlaybackContextTest.test_headersWithMaxKeySize")
add_test(PlaybackContextTest.test_headersWithMaliciousCharacters "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/PlaybackContextTest" "--gtest_filter=PlaybackContextTest.test_headersWithMaliciousCharacters")
add_test(OptionalTest.test_createEmptyOptional "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/OptionalTest" "--gtest_filter=OptionalTest.test_createEmptyOptional")
add_test(OptionalTest.test_createOptionalWithValue "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/OptionalTest" "--gtest_filter=OptionalTest.test_createOptionalWithValue")
add_test(OptionalTest.test_getValueOfOptionalWithValue "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/OptionalTest" "--gtest_filter=OptionalTest.test_getValueOfOptionalWithValue")
add_test(OptionalTest.test_getValueOfEmptyOptional "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/OptionalTest" "--gtest_filter=OptionalTest.test_getValueOfEmptyOptional")
add_test(OptionalTest.test_functionWithEmptyOptionalReturn "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/OptionalTest" "--gtest_filter=OptionalTest.test_functionWithEmptyOptionalReturn")
add_test(OptionalTest.test_functionWithNonEmptyOptionalReturn "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/OptionalTest" "--gtest_filter=OptionalTest.test_functionWithNonEmptyOptionalReturn")
add_test(OptionalTest.test_copyOptionalWithValue "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/OptionalTest" "--gtest_filter=OptionalTest.test_copyOptionalWithValue")
add_test(OptionalTest.test_copyEmptyOptional "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/OptionalTest" "--gtest_filter=OptionalTest.test_copyEmptyOptional")
add_test(OptionalTest.test_setNewValueForEmptyOptional "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/OptionalTest" "--gtest_filter=OptionalTest.test_setNewValueForEmptyOptional")
add_test(OptionalTest.test_setNewValueForNonEmptyOptional "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/OptionalTest" "--gtest_filter=OptionalTest.test_setNewValueForNonEmptyOptional")
add_test(OptionalTest.test_resetEmptyOptional "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/OptionalTest" "--gtest_filter=OptionalTest.test_resetEmptyOptional")
add_test(OptionalTest.test_resetNonEmptyOptional "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/OptionalTest" "--gtest_filter=OptionalTest.test_resetNonEmptyOptional")
add_test(OptionalTest.test_optionalObjectWithoutDefaultConstructor "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/OptionalTest" "--gtest_filter=OptionalTest.test_optionalObjectWithoutDefaultConstructor")
add_test(OptionalTest.test_constructorCallsMatchDestructorCalls "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/OptionalTest" "--gtest_filter=OptionalTest.test_constructorCallsMatchDestructorCalls")
add_test(OptionalTest.test_equalityOperator "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/OptionalTest" "--gtest_filter=OptionalTest.test_equalityOperator")
add_test(OptionalTest.test_inequalityOperator "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/OptionalTest" "--gtest_filter=OptionalTest.test_inequalityOperator")
add_test(AggregatedPowerResourceManagerTest.test_factoryMethodWithNullArgument "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/AggregatedPowerResourceManagerTest" "--gtest_filter=AggregatedPowerResourceManagerTest.test_factoryMethodWithNullArgument")
add_test(AggregatedPowerResourceManagerTest.test_createMultipleSameId "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/AggregatedPowerResourceManagerTest" "--gtest_filter=AggregatedPowerResourceManagerTest.test_createMultipleSameId")
add_test(AggregatedPowerResourceManagerTest.test_createMultipleSameLevel "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/AggregatedPowerResourceManagerTest" "--gtest_filter=AggregatedPowerResourceManagerTest.test_createMultipleSameLevel")
add_test(AggregatedPowerResourceManagerTest.test_createMultipleDifferentLevels "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/AggregatedPowerResourceManagerTest" "--gtest_filter=AggregatedPowerResourceManagerTest.test_createMultipleDifferentLevels")
add_test(AggregatedPowerResourceManagerTest.test_acquireMultipleSameLevel "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/AggregatedPowerResourceManagerTest" "--gtest_filter=AggregatedPowerResourceManagerTest.test_acquireMultipleSameLevel")
add_test(AggregatedPowerResourceManagerTest.test_acquireMultipleDifferentLevels "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/AggregatedPowerResourceManagerTest" "--gtest_filter=AggregatedPowerResourceManagerTest.test_acquireMultipleDifferentLevels")
add_test(AggregatedPowerResourceManagerTest.test_acquireNull "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/AggregatedPowerResourceManagerTest" "--gtest_filter=AggregatedPowerResourceManagerTest.test_acquireNull")
add_test(AggregatedPowerResourceManagerTest.test_acquireRefCounted "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/AggregatedPowerResourceManagerTest" "--gtest_filter=AggregatedPowerResourceManagerTest.test_acquireRefCounted")
add_test(AggregatedPowerResourceManagerTest.test_acquireNonRefCounted "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/AggregatedPowerResourceManagerTest" "--gtest_filter=AggregatedPowerResourceManagerTest.test_acquireNonRefCounted")
add_test(AggregatedPowerResourceManagerTest.test_releaseMultipleSameLevel "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/AggregatedPowerResourceManagerTest" "--gtest_filter=AggregatedPowerResourceManagerTest.test_releaseMultipleSameLevel")
add_test(AggregatedPowerResourceManagerTest.test_releaseMultipleDifferentLevels "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/AggregatedPowerResourceManagerTest" "--gtest_filter=AggregatedPowerResourceManagerTest.test_releaseMultipleDifferentLevels")
add_test(AggregatedPowerResourceManagerTest.test_releaseNull "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/AggregatedPowerResourceManagerTest" "--gtest_filter=AggregatedPowerResourceManagerTest.test_releaseNull")
add_test(AggregatedPowerResourceManagerTest.test_releaseRefCounted "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/AggregatedPowerResourceManagerTest" "--gtest_filter=AggregatedPowerResourceManagerTest.test_releaseRefCounted")
add_test(AggregatedPowerResourceManagerTest.test_releaseNonRefCounted "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/AggregatedPowerResourceManagerTest" "--gtest_filter=AggregatedPowerResourceManagerTest.test_releaseNonRefCounted")
add_test(AggregatedPowerResourceManagerTest.test_close "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/AggregatedPowerResourceManagerTest" "--gtest_filter=AggregatedPowerResourceManagerTest.test_close")
add_test(AggregatedPowerResourceManagerTest.test_closeCleanup "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/AggregatedPowerResourceManagerTest" "--gtest_filter=AggregatedPowerResourceManagerTest.test_closeCleanup")
add_test(AggregatedPowerResourceManagerTest.test_acquirePowerResourceLegacy "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/AggregatedPowerResourceManagerTest" "--gtest_filter=AggregatedPowerResourceManagerTest.test_acquirePowerResourceLegacy")
add_test(AggregatedPowerResourceManagerTest.test_releasePowerResourceLegacy "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/AggregatedPowerResourceManagerTest" "--gtest_filter=AggregatedPowerResourceManagerTest.test_releasePowerResourceLegacy")
add_test(AggregatedPowerResourceManagerTest.test_isPowerResourceAcquiredLegacy "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/AggregatedPowerResourceManagerTest" "--gtest_filter=AggregatedPowerResourceManagerTest.test_isPowerResourceAcquiredLegacy")
add_test(PowerResourceTest.test_createWithNull "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/PowerResourceTest" "--gtest_filter=PowerResourceTest.test_createWithNull")
add_test(PowerResourceTest.test_getters "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/PowerResourceTest" "--gtest_filter=PowerResourceTest.test_getters")
add_test(PowerResourceTest.test_acquire "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/PowerResourceTest" "--gtest_filter=PowerResourceTest.test_acquire")
add_test(PowerResourceTest.test_multiAcquire "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/PowerResourceTest" "--gtest_filter=PowerResourceTest.test_multiAcquire")
add_test(PowerResourceTest.test_destructor_releases "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/PowerResourceTest" "--gtest_filter=PowerResourceTest.test_destructor_releases")
add_test(PowerResourceTest.test_releaseNoAcquireSucceeds "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/PowerResourceTest" "--gtest_filter=PowerResourceTest.test_releaseNoAcquireSucceeds")
add_test(PowerResourceTest.test_release "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/PowerResourceTest" "--gtest_filter=PowerResourceTest.test_release")
add_test(PowerResourceTest.test_multiReleaseSymmetricalSucceeds "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/PowerResourceTest" "--gtest_filter=PowerResourceTest.test_multiReleaseSymmetricalSucceeds")
add_test(PowerResourceTest.test_multiReleaseAssymmetricalSucceeds "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/PowerResourceTest" "--gtest_filter=PowerResourceTest.test_multiReleaseAssymmetricalSucceeds")
add_test(PowerResourceTest.test_freezeMultiSucceeds "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/PowerResourceTest" "--gtest_filter=PowerResourceTest.test_freezeMultiSucceeds")
add_test(PowerResourceTest.test_frozenAcquireFails "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/PowerResourceTest" "--gtest_filter=PowerResourceTest.test_frozenAcquireFails")
add_test(PowerResourceTest.test_frozenReleaseFails "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/PowerResourceTest" "--gtest_filter=PowerResourceTest.test_frozenReleaseFails")
add_test(PowerResourceTest.test_multipleFreezeIdempotent "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/PowerResourceTest" "--gtest_filter=PowerResourceTest.test_multipleFreezeIdempotent")
add_test(PowerResourceTest.test_thawMulti "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/PowerResourceTest" "--gtest_filter=PowerResourceTest.test_thawMulti")
add_test(PowerResourceTest.test_thawAcquireSucceeds "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/PowerResourceTest" "--gtest_filter=PowerResourceTest.test_thawAcquireSucceeds")
add_test(PowerResourceTest.test_thawReleaseSucceeds "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/PowerResourceTest" "--gtest_filter=PowerResourceTest.test_thawReleaseSucceeds")
add_test(PowerResourceTest.test_multipleThawIdempotent "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/PowerResourceTest" "--gtest_filter=PowerResourceTest.test_multipleThawIdempotent")
add_test(PowerResourceTest.test_notRefCountedMultipleAcquireSuccceeds "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/PowerResourceTest" "--gtest_filter=PowerResourceTest.test_notRefCountedMultipleAcquireSuccceeds")
add_test(PowerResourceTest.test_notRefCountedReleaseSucceeds "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/PowerResourceTest" "--gtest_filter=PowerResourceTest.test_notRefCountedReleaseSucceeds")
add_test(WakeGuardTest.test_constructWithNull "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/WakeGuardTest" "--gtest_filter=WakeGuardTest.test_constructWithNull")
add_test(WakeGuardTest.test_createAcquires "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/WakeGuardTest" "--gtest_filter=WakeGuardTest.test_createAcquires")
add_test(WakeGuardTest.test_destructorReleases "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/WakeGuardTest" "--gtest_filter=WakeGuardTest.test_destructorReleases")
add_test(*/ConditionVariableWrapperTest.test_wait_NoThreadPowerResource_NotifyOne_Succeeds/* "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/ConditionVariableWrapperTest" "--gtest_filter=*/ConditionVariableWrapperTest.test_wait_NoThreadPowerResource_NotifyOne_Succeeds/*")
add_test(*/ConditionVariableWrapperTest.test_waitFor_NoThreadPowerResource_NotifyOne_Succeeds/* "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/ConditionVariableWrapperTest" "--gtest_filter=*/ConditionVariableWrapperTest.test_waitFor_NoThreadPowerResource_NotifyOne_Succeeds/*")
add_test(*/ConditionVariableWrapperTest.test_waitUntil_NoThreadPowerResource_NotifyOne_Succeeds/* "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/ConditionVariableWrapperTest" "--gtest_filter=*/ConditionVariableWrapperTest.test_waitUntil_NoThreadPowerResource_NotifyOne_Succeeds/*")
add_test(*/ConditionVariableWrapperTest.test_notifyOne_NoWaitingThreads_PowerCheck/* "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/ConditionVariableWrapperTest" "--gtest_filter=*/ConditionVariableWrapperTest.test_notifyOne_NoWaitingThreads_PowerCheck/*")
add_test(ConditionVariableWrapperPowerTest.test_wait_ThreadPowerResource_NotifyOne_Succeeds "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/ConditionVariableWrapperTest" "--gtest_filter=ConditionVariableWrapperPowerTest.test_wait_ThreadPowerResource_NotifyOne_Succeeds")
add_test(ConditionVariableWrapperPowerTest.test_waitFor_ThreadPowerResource_NotifyOne_Succeeds "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/ConditionVariableWrapperTest" "--gtest_filter=ConditionVariableWrapperPowerTest.test_waitFor_ThreadPowerResource_NotifyOne_Succeeds")
add_test(ConditionVariableWrapperPowerTest.test_waitUntil_ThreadPowerResource_NotifyOne_Succeeds "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/ConditionVariableWrapperTest" "--gtest_filter=ConditionVariableWrapperPowerTest.test_waitUntil_ThreadPowerResource_NotifyOne_Succeeds")
add_test(ConditionVariableWrapperPowerTest.test_wait_ThreadPowerResource_NotifyOne_PowerCheck_Succeeds "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/ConditionVariableWrapperTest" "--gtest_filter=ConditionVariableWrapperPowerTest.test_wait_ThreadPowerResource_NotifyOne_PowerCheck_Succeeds")
add_test(ConditionVariableWrapperPowerTest.test_wait_ThreadPowerResource_NotifyOne_PowerCheckMultiple_Succeeds "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/ConditionVariableWrapperTest" "--gtest_filter=ConditionVariableWrapperPowerTest.test_wait_ThreadPowerResource_NotifyOne_PowerCheckMultiple_Succeeds")
add_test(*/ConditionVariableWrapperTest.test_wait_NoThreadPowerResource_NotifyAll_Succeeds/* "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/ConditionVariableWrapperTest" "--gtest_filter=*/ConditionVariableWrapperTest.test_wait_NoThreadPowerResource_NotifyAll_Succeeds/*")
add_test(*/ConditionVariableWrapperTest.test_waitFor_NoThreadPowerResource_NotifyAll_Succeeds/* "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/ConditionVariableWrapperTest" "--gtest_filter=*/ConditionVariableWrapperTest.test_waitFor_NoThreadPowerResource_NotifyAll_Succeeds/*")
add_test(*/ConditionVariableWrapperTest.test_waitUntil_NoThreadPowerResource_NotifyAll_Succeeds/* "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/ConditionVariableWrapperTest" "--gtest_filter=*/ConditionVariableWrapperTest.test_waitUntil_NoThreadPowerResource_NotifyAll_Succeeds/*")
add_test(*/ConditionVariableWrapperTest.test_notifyAll_noWaitingThreads_PowerCheck/* "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/ConditionVariableWrapperTest" "--gtest_filter=*/ConditionVariableWrapperTest.test_notifyAll_noWaitingThreads_PowerCheck/*")
add_test(ConditionVariableWrapperPowerTest.test_wait_ThreadPowerResource_NotifyAll_Succeeds "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/ConditionVariableWrapperTest" "--gtest_filter=ConditionVariableWrapperPowerTest.test_wait_ThreadPowerResource_NotifyAll_Succeeds")
add_test(ConditionVariableWrapperPowerTest.test_waitFor_ThreadPowerResource_NotifyAll_Succeeds "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/ConditionVariableWrapperTest" "--gtest_filter=ConditionVariableWrapperPowerTest.test_waitFor_ThreadPowerResource_NotifyAll_Succeeds")
add_test(ConditionVariableWrapperPowerTest.test_waitUntil_ThreadPowerResource_NotifyAll_Succeeds "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/ConditionVariableWrapperTest" "--gtest_filter=ConditionVariableWrapperPowerTest.test_waitUntil_ThreadPowerResource_NotifyAll_Succeeds")
add_test(ConditionVariableWrapperPowerTest.test_wait_ThreadPowerResource_NotifyAll_PowerCheck_Succeeds "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/ConditionVariableWrapperTest" "--gtest_filter=ConditionVariableWrapperPowerTest.test_wait_ThreadPowerResource_NotifyAll_PowerCheck_Succeeds")
add_test(ConditionVariableWrapperPowerTest.test_wait_ThreadPowerResource_NotifyAll_PowerCheckMultiple_Succeeds "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/ConditionVariableWrapperTest" "--gtest_filter=ConditionVariableWrapperPowerTest.test_wait_ThreadPowerResource_NotifyAll_PowerCheckMultiple_Succeeds")
add_test(*/ConditionVariableWrapperTest.testTimer_waitFor_NoThreadPowerResource_NoNotify_ReturnsFalse/* "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/ConditionVariableWrapperTest" "--gtest_filter=*/ConditionVariableWrapperTest.testTimer_waitFor_NoThreadPowerResource_NoNotify_ReturnsFalse/*")
set_tests_properties(*/ConditionVariableWrapperTest.testTimer_waitFor_NoThreadPowerResource_NoNotify_ReturnsFalse/* PROPERTIES  LABELS "timertest")
add_test(*/ConditionVariableWrapperTest.testTimer_waitUntil_NoThreadPowerResource_NoNotify_ReturnsFalse/* "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/ConditionVariableWrapperTest" "--gtest_filter=*/ConditionVariableWrapperTest.testTimer_waitUntil_NoThreadPowerResource_NoNotify_ReturnsFalse/*")
set_tests_properties(*/ConditionVariableWrapperTest.testTimer_waitUntil_NoThreadPowerResource_NoNotify_ReturnsFalse/* PROPERTIES  LABELS "timertest")
add_test(*/ConditionVariableWrapperTest.testTimer_waitFor_NoPowerMonitor_NoNotify_ReturnsFalse/* "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/ConditionVariableWrapperTest" "--gtest_filter=*/ConditionVariableWrapperTest.testTimer_waitFor_NoPowerMonitor_NoNotify_ReturnsFalse/*")
set_tests_properties(*/ConditionVariableWrapperTest.testTimer_waitFor_NoPowerMonitor_NoNotify_ReturnsFalse/* PROPERTIES  LABELS "timertest")
add_test(*/ConditionVariableWrapperTest.testTimer_waitUntil_NoPowerMonitor_NoNotify_ReturnsFalse/* "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/ConditionVariableWrapperTest" "--gtest_filter=*/ConditionVariableWrapperTest.testTimer_waitUntil_NoPowerMonitor_NoNotify_ReturnsFalse/*")
set_tests_properties(*/ConditionVariableWrapperTest.testTimer_waitUntil_NoPowerMonitor_NoNotify_ReturnsFalse/* PROPERTIES  LABELS "timertest")
add_test(ConditionVariableWrapperPowerTest.testTimer_waitFor_ThreadPowerResource_NoNotify_ReturnsFalse "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/ConditionVariableWrapperTest" "--gtest_filter=ConditionVariableWrapperPowerTest.testTimer_waitFor_ThreadPowerResource_NoNotify_ReturnsFalse")
set_tests_properties(ConditionVariableWrapperPowerTest.testTimer_waitFor_ThreadPowerResource_NoNotify_ReturnsFalse PROPERTIES  LABELS "timertest")
add_test(ConditionVariableWrapperPowerTest.testTimer_waitFor_ThreadPowerResource_NoNotifySuccessfulPred_ReturnsTrue "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/ConditionVariableWrapperTest" "--gtest_filter=ConditionVariableWrapperPowerTest.testTimer_waitFor_ThreadPowerResource_NoNotifySuccessfulPred_ReturnsTrue")
set_tests_properties(ConditionVariableWrapperPowerTest.testTimer_waitFor_ThreadPowerResource_NoNotifySuccessfulPred_ReturnsTrue PROPERTIES  LABELS "timertest")
add_test(ConditionVariableWrapperPowerTest.testTimer_waitUntil_ThreadPowerResource_NoNotify_ReturnsFalse "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/ConditionVariableWrapperTest" "--gtest_filter=ConditionVariableWrapperPowerTest.testTimer_waitUntil_ThreadPowerResource_NoNotify_ReturnsFalse")
set_tests_properties(ConditionVariableWrapperPowerTest.testTimer_waitUntil_ThreadPowerResource_NoNotify_ReturnsFalse PROPERTIES  LABELS "timertest")
add_test(ConditionVariableWrapperPowerTest.testTimer_waitUntil_ThreadPowerResource_NoNotifySuccessfulPred_ReturnsTrue "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/ConditionVariableWrapperTest" "--gtest_filter=ConditionVariableWrapperPowerTest.testTimer_waitUntil_ThreadPowerResource_NoNotifySuccessfulPred_ReturnsTrue")
set_tests_properties(ConditionVariableWrapperPowerTest.testTimer_waitUntil_ThreadPowerResource_NoNotifySuccessfulPred_ReturnsTrue PROPERTIES  LABELS "timertest")
add_test(ConfigurationNodeTest.test_initializationAndAccess "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/ConfigurationNodeTest" "--gtest_filter=ConfigurationNodeTest.test_initializationAndAccess")
add_test(ConfigurationNodeTest.test_arrayElement "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/ConfigurationNodeTest" "--gtest_filter=ConfigurationNodeTest.test_arrayElement")
add_test(ConfigurationNodeTest.test_emptyArrayElement "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/ConfigurationNodeTest" "--gtest_filter=ConfigurationNodeTest.test_emptyArrayElement")
add_test(DataPointTest.test_buildDefault "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/DataPointTest" "--gtest_filter=DataPointTest.test_buildDefault")
add_test(DataPointTest.test_builderMethods "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/DataPointTest" "--gtest_filter=DataPointTest.test_builderMethods")
add_test(DataPointTest.test_counterDataPoint "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/DataPointTest" "--gtest_filter=DataPointTest.test_counterDataPoint")
add_test(DataPointTest.test_durationDataPoint "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/DataPointTest" "--gtest_filter=DataPointTest.test_durationDataPoint")
add_test(DataPointTest.test_negativeDurationDataPoint "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/DataPointTest" "--gtest_filter=DataPointTest.test_negativeDurationDataPoint")
add_test(DeviceInfoTest.test_buildDefault "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/DeviceInfoTest" "--gtest_filter=DeviceInfoTest.test_buildDefault")
add_test(DeviceInfoTest.test_buildCustomKeys "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/DeviceInfoTest" "--gtest_filter=DeviceInfoTest.test_buildCustomKeys")
add_test(DeviceInfoTest.test_buildEmptyStringsInvalid "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/DeviceInfoTest" "--gtest_filter=DeviceInfoTest.test_buildEmptyStringsInvalid")
add_test(EndianTest.test_SwapEndian16 "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/EndianTest" "--gtest_filter=EndianTest.test_SwapEndian16")
add_test(EndianTest.test_SwapEndian32 "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/EndianTest" "--gtest_filter=EndianTest.test_SwapEndian32")
add_test(ExecutorTest.testTimer_submitStdFunctionAndVerifyExecution "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/ExecutorTest" "--gtest_filter=ExecutorTest.testTimer_submitStdFunctionAndVerifyExecution")
set_tests_properties(ExecutorTest.testTimer_submitStdFunctionAndVerifyExecution PROPERTIES  LABELS "timertest")
add_test(ExecutorTest.testTimer_submitStdBindAndVerifyExecution "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/ExecutorTest" "--gtest_filter=ExecutorTest.testTimer_submitStdBindAndVerifyExecution")
set_tests_properties(ExecutorTest.testTimer_submitStdBindAndVerifyExecution PROPERTIES  LABELS "timertest")
add_test(ExecutorTest.testTimer_submitLambdaAndVerifyExecution "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/ExecutorTest" "--gtest_filter=ExecutorTest.testTimer_submitLambdaAndVerifyExecution")
set_tests_properties(ExecutorTest.testTimer_submitLambdaAndVerifyExecution PROPERTIES  LABELS "timertest")
add_test(ExecutorTest.testTimer_submitFunctionPointerAndVerifyExecution "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/ExecutorTest" "--gtest_filter=ExecutorTest.testTimer_submitFunctionPointerAndVerifyExecution")
set_tests_properties(ExecutorTest.testTimer_submitFunctionPointerAndVerifyExecution PROPERTIES  LABELS "timertest")
add_test(ExecutorTest.testTimer_submitFunctorAndVerifyExecution "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/ExecutorTest" "--gtest_filter=ExecutorTest.testTimer_submitFunctorAndVerifyExecution")
set_tests_properties(ExecutorTest.testTimer_submitFunctorAndVerifyExecution PROPERTIES  LABELS "timertest")
add_test(ExecutorTest.testTimer_submitFunctionWithPrimitiveReturnTypeNoArgsAndVerifyExecution "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/ExecutorTest" "--gtest_filter=ExecutorTest.testTimer_submitFunctionWithPrimitiveReturnTypeNoArgsAndVerifyExecution")
set_tests_properties(ExecutorTest.testTimer_submitFunctionWithPrimitiveReturnTypeNoArgsAndVerifyExecution PROPERTIES  LABELS "timertest")
add_test(ExecutorTest.testTimer_submitFunctionWithObjectReturnTypeNoArgsAndVerifyExecution "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/ExecutorTest" "--gtest_filter=ExecutorTest.testTimer_submitFunctionWithObjectReturnTypeNoArgsAndVerifyExecution")
set_tests_properties(ExecutorTest.testTimer_submitFunctionWithObjectReturnTypeNoArgsAndVerifyExecution PROPERTIES  LABELS "timertest")
add_test(ExecutorTest.testTimer_submitFunctionWithNoReturnTypePrimitiveArgsAndVerifyExecution "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/ExecutorTest" "--gtest_filter=ExecutorTest.testTimer_submitFunctionWithNoReturnTypePrimitiveArgsAndVerifyExecution")
set_tests_properties(ExecutorTest.testTimer_submitFunctionWithNoReturnTypePrimitiveArgsAndVerifyExecution PROPERTIES  LABELS "timertest")
add_test(ExecutorTest.testTimer_submitFunctionWithNoReturnTypeObjectArgsAndVerifyExecution "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/ExecutorTest" "--gtest_filter=ExecutorTest.testTimer_submitFunctionWithNoReturnTypeObjectArgsAndVerifyExecution")
set_tests_properties(ExecutorTest.testTimer_submitFunctionWithNoReturnTypeObjectArgsAndVerifyExecution PROPERTIES  LABELS "timertest")
add_test(ExecutorTest.testTimer_submitFunctionWithPrimitiveReturnTypeObjectArgsAndVerifyExecution "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/ExecutorTest" "--gtest_filter=ExecutorTest.testTimer_submitFunctionWithPrimitiveReturnTypeObjectArgsAndVerifyExecution")
set_tests_properties(ExecutorTest.testTimer_submitFunctionWithPrimitiveReturnTypeObjectArgsAndVerifyExecution PROPERTIES  LABELS "timertest")
add_test(ExecutorTest.testTimer_submitFunctionWithObjectReturnTypePrimitiveArgsAndVerifyExecution "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/ExecutorTest" "--gtest_filter=ExecutorTest.testTimer_submitFunctionWithObjectReturnTypePrimitiveArgsAndVerifyExecution")
set_tests_properties(ExecutorTest.testTimer_submitFunctionWithObjectReturnTypePrimitiveArgsAndVerifyExecution PROPERTIES  LABELS "timertest")
add_test(ExecutorTest.testTimer_submitFunctionWithPrimitiveReturnTypePrimitiveArgsAndVerifyExecution "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/ExecutorTest" "--gtest_filter=ExecutorTest.testTimer_submitFunctionWithPrimitiveReturnTypePrimitiveArgsAndVerifyExecution")
set_tests_properties(ExecutorTest.testTimer_submitFunctionWithPrimitiveReturnTypePrimitiveArgsAndVerifyExecution PROPERTIES  LABELS "timertest")
add_test(ExecutorTest.testTimer_submitFunctionWithObjectReturnTypeObjectArgsAndVerifyExecution "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/ExecutorTest" "--gtest_filter=ExecutorTest.testTimer_submitFunctionWithObjectReturnTypeObjectArgsAndVerifyExecution")
set_tests_properties(ExecutorTest.testTimer_submitFunctionWithObjectReturnTypeObjectArgsAndVerifyExecution PROPERTIES  LABELS "timertest")
add_test(ExecutorTest.testTimer_submitToFront "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/ExecutorTest" "--gtest_filter=ExecutorTest.testTimer_submitToFront")
set_tests_properties(ExecutorTest.testTimer_submitToFront PROPERTIES  LABELS "timertest")
add_test(ExecutorTest.testTimer_executionOrderEqualToSubmitOrder "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/ExecutorTest" "--gtest_filter=ExecutorTest.testTimer_executionOrderEqualToSubmitOrder")
set_tests_properties(ExecutorTest.testTimer_executionOrderEqualToSubmitOrder PROPERTIES  LABELS "timertest")
add_test(ExecutorTest.testTimer_futureWaitsForTaskCleanup "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/ExecutorTest" "--gtest_filter=ExecutorTest.testTimer_futureWaitsForTaskCleanup")
set_tests_properties(ExecutorTest.testTimer_futureWaitsForTaskCleanup PROPERTIES  LABELS "timertest")
add_test(ExecutorTest.testTimer_shutdown "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/ExecutorTest" "--gtest_filter=ExecutorTest.testTimer_shutdown")
set_tests_properties(ExecutorTest.testTimer_shutdown PROPERTIES  LABELS "timertest")
add_test(ExecutorTest.testTimer_pushAfterExecutordownFail "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/ExecutorTest" "--gtest_filter=ExecutorTest.testTimer_pushAfterExecutordownFail")
set_tests_properties(ExecutorTest.testTimer_pushAfterExecutordownFail PROPERTIES  LABELS "timertest")
add_test(ExecutorTest.testTimer_shutdownCancelJob "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/ExecutorTest" "--gtest_filter=ExecutorTest.testTimer_shutdownCancelJob")
set_tests_properties(ExecutorTest.testTimer_shutdownCancelJob PROPERTIES  LABELS "timertest")
add_test(HTTPContentTest.test_readStatusCodeSuccess "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/HTTPContentTest" "--gtest_filter=HTTPContentTest.test_readStatusCodeSuccess")
add_test(HTTPContentTest.test_readStatusCodePartialContentSuccess "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/HTTPContentTest" "--gtest_filter=HTTPContentTest.test_readStatusCodePartialContentSuccess")
add_test(HTTPContentTest.test_readStatusCodeNotSuccess "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/HTTPContentTest" "--gtest_filter=HTTPContentTest.test_readStatusCodeNotSuccess")
add_test(HTTPContentTest.test_readStatusCodeMoreThanOnce "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/HTTPContentTest" "--gtest_filter=HTTPContentTest.test_readStatusCodeMoreThanOnce")
add_test(HTTPContentTest.test_readContentTypeMoreThanOnce "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/HTTPContentTest" "--gtest_filter=HTTPContentTest.test_readContentTypeMoreThanOnce")
add_test(HTTPContentTest.test_getDataStream "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/HTTPContentTest" "--gtest_filter=HTTPContentTest.test_getDataStream")
add_test(JsonGeneratorTest.test_emptyJson "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/JSONGeneratorTest" "--gtest_filter=JsonGeneratorTest.test_emptyJson")
add_test(JsonGeneratorTest.test_jsonObject "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/JSONGeneratorTest" "--gtest_filter=JsonGeneratorTest.test_jsonObject")
add_test(JsonGeneratorTest.test_jsonInt "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/JSONGeneratorTest" "--gtest_filter=JsonGeneratorTest.test_jsonInt")
add_test(JsonGeneratorTest.test_jsonLong "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/JSONGeneratorTest" "--gtest_filter=JsonGeneratorTest.test_jsonLong")
add_test(JsonGeneratorTest.test_jsonUInt "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/JSONGeneratorTest" "--gtest_filter=JsonGeneratorTest.test_jsonUInt")
add_test(JsonGeneratorTest.test_jsonULong "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/JSONGeneratorTest" "--gtest_filter=JsonGeneratorTest.test_jsonULong")
add_test(JsonGeneratorTest.test_jsonBool "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/JSONGeneratorTest" "--gtest_filter=JsonGeneratorTest.test_jsonBool")
add_test(JsonGeneratorTest.test_jsonDouble "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/JSONGeneratorTest" "--gtest_filter=JsonGeneratorTest.test_jsonDouble")
add_test(JsonGeneratorTest.test_jsonCString "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/JSONGeneratorTest" "--gtest_filter=JsonGeneratorTest.test_jsonCString")
add_test(JsonGeneratorTest.test_jsonNullCString "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/JSONGeneratorTest" "--gtest_filter=JsonGeneratorTest.test_jsonNullCString")
add_test(JsonGeneratorTest.test_jsonStringArray "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/JSONGeneratorTest" "--gtest_filter=JsonGeneratorTest.test_jsonStringArray")
add_test(JsonGeneratorTest.test_jsonArray "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/JSONGeneratorTest" "--gtest_filter=JsonGeneratorTest.test_jsonArray")
add_test(JsonGeneratorTest.test_jsonEmptyList "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/JSONGeneratorTest" "--gtest_filter=JsonGeneratorTest.test_jsonEmptyList")
add_test(JsonGeneratorTest.test_jsonRawJsonMember "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/JSONGeneratorTest" "--gtest_filter=JsonGeneratorTest.test_jsonRawJsonMember")
add_test(JsonGeneratorTest.test_jsonRawJsonMemberFailed "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/JSONGeneratorTest" "--gtest_filter=JsonGeneratorTest.test_jsonRawJsonMemberFailed")
add_test(JsonGeneratorTest.test_closeTooMany "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/JSONGeneratorTest" "--gtest_filter=JsonGeneratorTest.test_closeTooMany")
add_test(JsonGeneratorTest.test_openObjects "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/JSONGeneratorTest" "--gtest_filter=JsonGeneratorTest.test_openObjects")
add_test(JsonGeneratorTest.test_finalizeObjects "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/JSONGeneratorTest" "--gtest_filter=JsonGeneratorTest.test_finalizeObjects")
add_test(JsonGeneratorTest.test_addMemberAfterFinalize "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/JSONGeneratorTest" "--gtest_filter=JsonGeneratorTest.test_addMemberAfterFinalize")
add_test(JsonGeneratorTest.test_jsonCollectionOfStringArray "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/JSONGeneratorTest" "--gtest_filter=JsonGeneratorTest.test_jsonCollectionOfStringArray")
add_test(JsonGeneratorTest.test_jsonCollectionOfEmptyCollection "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/JSONGeneratorTest" "--gtest_filter=JsonGeneratorTest.test_jsonCollectionOfEmptyCollection")
add_test(JsonGeneratorTest.test_jsonCollectionOfEmptyStringArray "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/JSONGeneratorTest" "--gtest_filter=JsonGeneratorTest.test_jsonCollectionOfEmptyStringArray")
add_test(JSONUtilTest.test_validJsonChildObjectAsString "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/JSONUtilTest" "--gtest_filter=JSONUtilTest.test_validJsonChildObjectAsString")
add_test(JSONUtilTest.test_validJsonScalarString "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/JSONUtilTest" "--gtest_filter=JSONUtilTest.test_validJsonScalarString")
add_test(JSONUtilTest.test_validJsonInteger "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/JSONUtilTest" "--gtest_filter=JSONUtilTest.test_validJsonInteger")
add_test(JSONUtilTest.test_retrieveValueStringBasedInt64FromInvalidJSON "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/JSONUtilTest" "--gtest_filter=JSONUtilTest.test_retrieveValueStringBasedInt64FromInvalidJSON")
add_test(JSONUtilTest.test_retrieveValueStringBasedStringFromInvalidJSON "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/JSONUtilTest" "--gtest_filter=JSONUtilTest.test_retrieveValueStringBasedStringFromInvalidJSON")
add_test(JSONUtilTest.test_retrieveValueStringBasedWithIncorrectKey "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/JSONUtilTest" "--gtest_filter=JSONUtilTest.test_retrieveValueStringBasedWithIncorrectKey")
add_test(JSONUtilTest.test_retrieveValueStringBasedWithNull "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/JSONUtilTest" "--gtest_filter=JSONUtilTest.test_retrieveValueStringBasedWithNull")
add_test(JSONUtilTest.test_retrieveValueDocumentBasedWithInvalidValueType "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/JSONUtilTest" "--gtest_filter=JSONUtilTest.test_retrieveValueDocumentBasedWithInvalidValueType")
add_test(JSONUtilTest.test_retrieveValueDocumentBasedWithNull "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/JSONUtilTest" "--gtest_filter=JSONUtilTest.test_retrieveValueDocumentBasedWithNull")
add_test(JSONUtilTest.test_retrieveValueDocumentBasedWithValidInt64 "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/JSONUtilTest" "--gtest_filter=JSONUtilTest.test_retrieveValueDocumentBasedWithValidInt64")
add_test(JSONUtilTest.test_findNodeNull "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/JSONUtilTest" "--gtest_filter=JSONUtilTest.test_findNodeNull")
add_test(JSONUtilTest.test_findNodeKeyExists "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/JSONUtilTest" "--gtest_filter=JSONUtilTest.test_findNodeKeyExists")
add_test(JSONUtilTest.test_findNodeKeyMissing "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/JSONUtilTest" "--gtest_filter=JSONUtilTest.test_findNodeKeyMissing")
add_test(JSONUtilTest.test_parseJSONNullOutputParam "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/JSONUtilTest" "--gtest_filter=JSONUtilTest.test_parseJSONNullOutputParam")
add_test(JSONUtilTest.test_parseJSONValidJSON "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/JSONUtilTest" "--gtest_filter=JSONUtilTest.test_parseJSONValidJSON")
add_test(JSONUtilTest.test_parseJSONInvalidJSON "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/JSONUtilTest" "--gtest_filter=JSONUtilTest.test_parseJSONInvalidJSON")
add_test(JSONUtilTest.test_convertToStringValueWithString "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/JSONUtilTest" "--gtest_filter=JSONUtilTest.test_convertToStringValueWithString")
add_test(JSONUtilTest.test_convertToStringValueWithObject "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/JSONUtilTest" "--gtest_filter=JSONUtilTest.test_convertToStringValueWithObject")
add_test(JSONUtilTest.test_convertToStringValueWithInvalidValue "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/JSONUtilTest" "--gtest_filter=JSONUtilTest.test_convertToStringValueWithInvalidValue")
add_test(JSONUtilTest.test_convertToStringValueWithNullOutputParam "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/JSONUtilTest" "--gtest_filter=JSONUtilTest.test_convertToStringValueWithNullOutputParam")
add_test(JSONUtilTest.test_convertToInt64ValueWithInt64 "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/JSONUtilTest" "--gtest_filter=JSONUtilTest.test_convertToInt64ValueWithInt64")
add_test(JSONUtilTest.test_convertToInt64ValueWithDouble "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/JSONUtilTest" "--gtest_filter=JSONUtilTest.test_convertToInt64ValueWithDouble")
add_test(JSONUtilTest.test_convertToUint64ValueWithNullOutputParam "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/JSONUtilTest" "--gtest_filter=JSONUtilTest.test_convertToUint64ValueWithNullOutputParam")
add_test(JSONUtilTest.test_convertToUint64ValueWithUint64 "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/JSONUtilTest" "--gtest_filter=JSONUtilTest.test_convertToUint64ValueWithUint64")
add_test(JSONUtilTest.test_convertToUint64ValueWithDouble "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/JSONUtilTest" "--gtest_filter=JSONUtilTest.test_convertToUint64ValueWithDouble")
add_test(JSONUtilTest.test_convertToInt64ValueWithNullOutputParam "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/JSONUtilTest" "--gtest_filter=JSONUtilTest.test_convertToInt64ValueWithNullOutputParam")
add_test(JSONUtilTest.test_convertToBoolValueWithNullOutputParam "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/JSONUtilTest" "--gtest_filter=JSONUtilTest.test_convertToBoolValueWithNullOutputParam")
add_test(JSONUtilTest.test_convertToBoolValueWithNonBool "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/JSONUtilTest" "--gtest_filter=JSONUtilTest.test_convertToBoolValueWithNonBool")
add_test(JSONUtilTest.test_convertToBoolValueWithBool "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/JSONUtilTest" "--gtest_filter=JSONUtilTest.test_convertToBoolValueWithBool")
add_test(JSONUtilTest.test_retrieveStringArraySucceed "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/JSONUtilTest" "--gtest_filter=JSONUtilTest.test_retrieveStringArraySucceed")
add_test(JSONUtilTest.test_retrieveStringArrayEmpty "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/JSONUtilTest" "--gtest_filter=JSONUtilTest.test_retrieveStringArrayEmpty")
add_test(JSONUtilTest.test_retrieveStringArrayNonArray "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/JSONUtilTest" "--gtest_filter=JSONUtilTest.test_retrieveStringArrayNonArray")
add_test(JSONUtilTest.test_retrieveStringArrayNonJson "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/JSONUtilTest" "--gtest_filter=JSONUtilTest.test_retrieveStringArrayNonJson")
add_test(JSONUtilTest.test_retrieveStringArrayWithNonStringArrayFails "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/JSONUtilTest" "--gtest_filter=JSONUtilTest.test_retrieveStringArrayWithNonStringArrayFails")
add_test(JSONUtilTest.test_convertToJsonStringFromEmptySet "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/JSONUtilTest" "--gtest_filter=JSONUtilTest.test_convertToJsonStringFromEmptySet")
add_test(JSONUtilTest.test_convertToJsonStringFromStringSet "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/JSONUtilTest" "--gtest_filter=JSONUtilTest.test_convertToJsonStringFromStringSet")
add_test(JSONUtilTest.test_convertToJsonFromStringVector "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/JSONUtilTest" "--gtest_filter=JSONUtilTest.test_convertToJsonFromStringVector")
add_test(JSONUtilTest.test_retrieveElementsWithKeySucceed "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/JSONUtilTest" "--gtest_filter=JSONUtilTest.test_retrieveElementsWithKeySucceed")
add_test(JSONUtilTest.test_retrieveMixStringNonStringElementsWithKeySucceed "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/JSONUtilTest" "--gtest_filter=JSONUtilTest.test_retrieveMixStringNonStringElementsWithKeySucceed")
add_test(JSONUtilTest.test_retrieveElementsWithKeyEmptyArray "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/JSONUtilTest" "--gtest_filter=JSONUtilTest.test_retrieveElementsWithKeyEmptyArray")
add_test(JSONUtilTest.test_retrieveElementsWithKeyNonArray "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/JSONUtilTest" "--gtest_filter=JSONUtilTest.test_retrieveElementsWithKeyNonArray")
add_test(JSONUtilTest.test_retrieveElementsWithKeyMissing "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/JSONUtilTest" "--gtest_filter=JSONUtilTest.test_retrieveElementsWithKeyMissing")
add_test(JSONUtilTest.test_retrieveArrayOfElementsWithKeySucceed "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/JSONUtilTest" "--gtest_filter=JSONUtilTest.test_retrieveArrayOfElementsWithKeySucceed")
add_test(JSONUtilTest.test_retrieveStringMapFromArrayOnlyKeyEntry "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/JSONUtilTest" "--gtest_filter=JSONUtilTest.test_retrieveStringMapFromArrayOnlyKeyEntry")
add_test(JSONUtilTest.test_retrieveStringMapFromArrayInvalidEntry "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/JSONUtilTest" "--gtest_filter=JSONUtilTest.test_retrieveStringMapFromArrayInvalidEntry")
add_test(JSONUtilTest.test_retrieveStringMapFromArray "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/JSONUtilTest" "--gtest_filter=JSONUtilTest.test_retrieveStringMapFromArray")
add_test(JSONUtilTest.test_retrieveStringMapFromArrayMultiple "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/JSONUtilTest" "--gtest_filter=JSONUtilTest.test_retrieveStringMapFromArrayMultiple")
add_test(JSONUtilTest.test_retrieveStringMapFromArrayAll "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/JSONUtilTest" "--gtest_filter=JSONUtilTest.test_retrieveStringMapFromArrayAll")
add_test(JSONUtilTest.test_retrieveStringMapFromArrayNoneFew "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/JSONUtilTest" "--gtest_filter=JSONUtilTest.test_retrieveStringMapFromArrayNoneFew")
add_test(JSONUtilTest.test_retrieveStringMapFromArrayNoneAll "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/JSONUtilTest" "--gtest_filter=JSONUtilTest.test_retrieveStringMapFromArrayNoneAll")
add_test(JSONUtilTest.test_retrieveArrayStringMapFromArray "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/JSONUtilTest" "--gtest_filter=JSONUtilTest.test_retrieveArrayStringMapFromArray")
add_test(JSONUtilTest.test_retrieveArrayStringMapFromArrayInvalidEntry "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/JSONUtilTest" "--gtest_filter=JSONUtilTest.test_retrieveArrayStringMapFromArrayInvalidEntry")
add_test(JSONUtilTest.test_retrieveArrayStringMapFromArrayInvalidKey "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/JSONUtilTest" "--gtest_filter=JSONUtilTest.test_retrieveArrayStringMapFromArrayInvalidKey")
add_test(JSONUtilTest.test_retrieveArrayStringMapFromArrayEmptyArray "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/JSONUtilTest" "--gtest_filter=JSONUtilTest.test_retrieveArrayStringMapFromArrayEmptyArray")
add_test(JSONUtilTest.test_retrieveArrayStringMapFromArrayEmptyMap "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/JSONUtilTest" "--gtest_filter=JSONUtilTest.test_retrieveArrayStringMapFromArrayEmptyMap")
add_test(LogEntryStreamTest.test_emptyStream "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/LogEntryStreamTest" "--gtest_filter=LogEntryStreamTest.test_emptyStream")
add_test(LogEntryStreamTest.test_shortString "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/LogEntryStreamTest" "--gtest_filter=LogEntryStreamTest.test_shortString")
add_test(LogEntryStreamTest.test_mediumString "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/LogEntryStreamTest" "--gtest_filter=LogEntryStreamTest.test_mediumString")
add_test(LogEntryStreamTest.test_longString "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/LogEntryStreamTest" "--gtest_filter=LogEntryStreamTest.test_longString")
add_test(LogEntryStreamTest.test_aFewStrings "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/LogEntryStreamTest" "--gtest_filter=LogEntryStreamTest.test_aFewStrings")
add_test(LogEntryStreamTest.test_aLotOfStrings "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/LogEntryStreamTest" "--gtest_filter=LogEntryStreamTest.test_aLotOfStrings")
add_test(LoggerTest.test_logDebug9Level "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/LoggerTest" "--gtest_filter=LoggerTest.test_logDebug9Level")
add_test(LoggerTest.test_logDebug8Level "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/LoggerTest" "--gtest_filter=LoggerTest.test_logDebug8Level")
add_test(LoggerTest.test_logDebug7Level "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/LoggerTest" "--gtest_filter=LoggerTest.test_logDebug7Level")
add_test(LoggerTest.test_logDebug6Level "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/LoggerTest" "--gtest_filter=LoggerTest.test_logDebug6Level")
add_test(LoggerTest.test_logDebug5Level "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/LoggerTest" "--gtest_filter=LoggerTest.test_logDebug5Level")
add_test(LoggerTest.test_logDebug4Level "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/LoggerTest" "--gtest_filter=LoggerTest.test_logDebug4Level")
add_test(LoggerTest.test_logDebug3Level "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/LoggerTest" "--gtest_filter=LoggerTest.test_logDebug3Level")
add_test(LoggerTest.test_logDebug2Level "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/LoggerTest" "--gtest_filter=LoggerTest.test_logDebug2Level")
add_test(LoggerTest.test_logDebug1Level "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/LoggerTest" "--gtest_filter=LoggerTest.test_logDebug1Level")
add_test(LoggerTest.test_logDebug0Level "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/LoggerTest" "--gtest_filter=LoggerTest.test_logDebug0Level")
add_test(LoggerTest.test_logInfoLevel "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/LoggerTest" "--gtest_filter=LoggerTest.test_logInfoLevel")
add_test(LoggerTest.test_logWarnLevel "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/LoggerTest" "--gtest_filter=LoggerTest.test_logWarnLevel")
add_test(LoggerTest.test_logErrorLevel "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/LoggerTest" "--gtest_filter=LoggerTest.test_logErrorLevel")
add_test(LoggerTest.test_logCriticalLevel "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/LoggerTest" "--gtest_filter=LoggerTest.test_logCriticalLevel")
add_test(LoggerTest.test_logNoneLevel "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/LoggerTest" "--gtest_filter=LoggerTest.test_logNoneLevel")
add_test(LoggerTest.test_nullInputs "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/LoggerTest" "--gtest_filter=LoggerTest.test_nullInputs")
add_test(LoggerTest.test_verifyTime "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/LoggerTest" "--gtest_filter=LoggerTest.test_verifyTime")
add_test(LoggerTest.test_verifyThreadMoniker "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/LoggerTest" "--gtest_filter=LoggerTest.test_verifyThreadMoniker")
add_test(LoggerTest.test_verifySource "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/LoggerTest" "--gtest_filter=LoggerTest.test_verifySource")
add_test(LoggerTest.test_verifyEvent "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/LoggerTest" "--gtest_filter=LoggerTest.test_verifyEvent")
add_test(LoggerTest.test_verifyMetadata "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/LoggerTest" "--gtest_filter=LoggerTest.test_verifyMetadata")
add_test(LoggerTest.test_verifyMessage "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/LoggerTest" "--gtest_filter=LoggerTest.test_verifyMessage")
add_test(LoggerTest.test_sensitiveDataSuppressed "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/LoggerTest" "--gtest_filter=LoggerTest.test_sensitiveDataSuppressed")
add_test(LoggerTest.test_obfuscatedDataIsMangled "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/LoggerTest" "--gtest_filter=LoggerTest.test_obfuscatedDataIsMangled")
add_test(LoggerTest.test_moduleLoggerObserver "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/LoggerTest" "--gtest_filter=LoggerTest.test_moduleLoggerObserver")
add_test(LoggerTest.test_multipleModuleLoggerObservers "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/LoggerTest" "--gtest_filter=LoggerTest.test_multipleModuleLoggerObservers")
add_test(LoggerTest.test_changeSinkLogger "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/LoggerTest" "--gtest_filter=LoggerTest.test_changeSinkLogger")
add_test(MIMEParserTest.test_encodingSanity "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/MIMEParserTest" "--gtest_filter=MIMEParserTest.test_encodingSanity")
add_test(MIMEParserTest.test_decodingBoundariesSendBoundaryWithoutCRLF "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/MIMEParserTest" "--gtest_filter=MIMEParserTest.test_decodingBoundariesSendBoundaryWithoutCRLF")
add_test(MIMEParserTest.test_decodingBoundariesSendBoundaryWithTerminatorShouldIgnoreEpilogue "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/MIMEParserTest" "--gtest_filter=MIMEParserTest.test_decodingBoundariesSendBoundaryWithTerminatorShouldIgnoreEpilogue")
add_test(MIMEParserTest.test_decodingBoundariesSendDuplicatedBoundaryAsHeader "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/MIMEParserTest" "--gtest_filter=MIMEParserTest.test_decodingBoundariesSendDuplicatedBoundaryAsHeader")
add_test(MIMEParserTest.test_decodingBoundariesAvs "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/MIMEParserTest" "--gtest_filter=MIMEParserTest.test_decodingBoundariesAvs")
add_test(MIMEParserTest.test_decodingBoundariesSendFakeBoundaryAsData "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/MIMEParserTest" "--gtest_filter=MIMEParserTest.test_decodingBoundariesSendFakeBoundaryAsData")
add_test(MIMEParserTest.test_decodingBoundariesSendFakeBoundaryAsOnlyData "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/MIMEParserTest" "--gtest_filter=MIMEParserTest.test_decodingBoundariesSendFakeBoundaryAsOnlyData")
add_test(MIMEParserTest.test_decodingBoundariesSendBoundaryWithCRLF "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/MIMEParserTest" "--gtest_filter=MIMEParserTest.test_decodingBoundariesSendBoundaryWithCRLF")
add_test(MIMEParserTest.test_decodingBoundariesSendEndBoundaryWithoutCRLF "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/MIMEParserTest" "--gtest_filter=MIMEParserTest.test_decodingBoundariesSendEndBoundaryWithoutCRLF")
add_test(MIMEParserTest.test_decodingBoundariesSendBoundaryWithData "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/MIMEParserTest" "--gtest_filter=MIMEParserTest.test_decodingBoundariesSendBoundaryWithData")
add_test(MIMEParserTest.test_decodingSanity "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/MIMEParserTest" "--gtest_filter=MIMEParserTest.test_decodingSanity")
add_test(MIMEParserTest.test_singlePayloadSinglePass "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/MIMEParserTest" "--gtest_filter=MIMEParserTest.test_singlePayloadSinglePass")
add_test(MIMEParserTest.test_singlePayloadMultiplePasses "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/MIMEParserTest" "--gtest_filter=MIMEParserTest.test_singlePayloadMultiplePasses")
add_test(MIMEParserTest.test_multiplePayloadsSinglePass "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/MIMEParserTest" "--gtest_filter=MIMEParserTest.test_multiplePayloadsSinglePass")
add_test(MIMEParserTest.test_multiplePayloadsMultiplePasses "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/MIMEParserTest" "--gtest_filter=MIMEParserTest.test_multiplePayloadsMultiplePasses")
add_test(MIMEParserTest.test_duplicateBoundaries "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/MIMEParserTest" "--gtest_filter=MIMEParserTest.test_duplicateBoundaries")
add_test(MIMEParserTest.test_aBORT "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/MIMEParserTest" "--gtest_filter=MIMEParserTest.test_aBORT")
add_test(MIMEParserTest.test_pAUSE "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/MIMEParserTest" "--gtest_filter=MIMEParserTest.test_pAUSE")
add_test(MIMEParserTest.test_variableChunkSizes "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/MIMEParserTest" "--gtest_filter=MIMEParserTest.test_variableChunkSizes")
add_test(MIMEParserTest.test_prefixCases "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/MIMEParserTest" "--gtest_filter=MIMEParserTest.test_prefixCases")
add_test(MacAddressStringTest.test_createWithInvalidHexDigits "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/MacAddressStringTest" "--gtest_filter=MacAddressStringTest.test_createWithInvalidHexDigits")
add_test(MacAddressStringTest.test_createWithInvalidNumberOfOctets "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/MacAddressStringTest" "--gtest_filter=MacAddressStringTest.test_createWithInvalidNumberOfOctets")
add_test(MacAddressStringTest.test_createWithNoDividers "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/MacAddressStringTest" "--gtest_filter=MacAddressStringTest.test_createWithNoDividers")
add_test(MacAddressStringTest.test_createWithInvalidDividers "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/MacAddressStringTest" "--gtest_filter=MacAddressStringTest.test_createWithInvalidDividers")
add_test(MacAddressStringTest.test_createWithValidMacAddress "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/MacAddressStringTest" "--gtest_filter=MacAddressStringTest.test_createWithValidMacAddress")
add_test(MacAddressStringTest.test_createWithTruncatedMacAddress "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/MacAddressStringTest" "--gtest_filter=MacAddressStringTest.test_createWithTruncatedMacAddress")
add_test(MetricEventTest.test_buildDefault "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/MetricEventTest" "--gtest_filter=MetricEventTest.test_buildDefault")
add_test(MetricEventTest.test_addDataPoint "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/MetricEventTest" "--gtest_filter=MetricEventTest.test_addDataPoint")
add_test(MetricEventTest.test_removeDataPointByObject "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/MetricEventTest" "--gtest_filter=MetricEventTest.test_removeDataPointByObject")
add_test(MetricEventTest.test_removeDataPointByNameAndDataType "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/MetricEventTest" "--gtest_filter=MetricEventTest.test_removeDataPointByNameAndDataType")
add_test(MetricEventTest.test_removeDataPoints "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/MetricEventTest" "--gtest_filter=MetricEventTest.test_removeDataPoints")
add_test(MetricEventTest.test_clear "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/MetricEventTest" "--gtest_filter=MetricEventTest.test_clear")
add_test(MultiTimerTest.test_taskGetsCalled "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/MultiTimerTest" "--gtest_filter=MultiTimerTest.test_taskGetsCalled")
add_test(MultiTimerTest.testTimer_cancelledTaskShouldNotRun "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/MultiTimerTest" "--gtest_filter=MultiTimerTest.testTimer_cancelledTaskShouldNotRun")
set_tests_properties(MultiTimerTest.testTimer_cancelledTaskShouldNotRun PROPERTIES  LABELS "timertest")
add_test(MultiTimerTest.test_executionOrderFollowExpirationTime "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/MultiTimerTest" "--gtest_filter=MultiTimerTest.test_executionOrderFollowExpirationTime")
add_test(MultiTimerTest.test_multipleTasksGetCalledInOrder "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/MultiTimerTest" "--gtest_filter=MultiTimerTest.test_multipleTasksGetCalledInOrder")
add_test(PooledMediaPlayerFactoryTest.test_acquirePlayers "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/PooledMediaPlayerFactoryTest" "--gtest_filter=PooledMediaPlayerFactoryTest.test_acquirePlayers")
add_test(PooledMediaPlayerFactoryTest.test_releasePlayers "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/PooledMediaPlayerFactoryTest" "--gtest_filter=PooledMediaPlayerFactoryTest.test_releasePlayers")
add_test(PooledMediaPlayerFactoryTest.test_recyclePlayers "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/PooledMediaPlayerFactoryTest" "--gtest_filter=PooledMediaPlayerFactoryTest.test_recyclePlayers")
add_test(PooledMediaPlayerFactoryTest.test_onReadyCallback "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/PooledMediaPlayerFactoryTest" "--gtest_filter=PooledMediaPlayerFactoryTest.test_onReadyCallback")
add_test(PooledMediaPlayerFactoryTest.test_isMediaPlayerAvailable "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/PooledMediaPlayerFactoryTest" "--gtest_filter=PooledMediaPlayerFactoryTest.test_isMediaPlayerAvailable")
add_test(RequiresShutdownTest.test_allTestCases "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/RequiresShutdownTest" "--gtest_filter=RequiresShutdownTest.test_allTestCases")
add_test(SafeCTimeAccessTest.test_getGmtimeNullReturnValue "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/SafeTimeAccessTest" "--gtest_filter=SafeCTimeAccessTest.test_getGmtimeNullReturnValue")
add_test(SafeCTimeAccessTest.test_getLocaltimeNullReturnValue "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/SafeTimeAccessTest" "--gtest_filter=SafeCTimeAccessTest.test_getLocaltimeNullReturnValue")
add_test(SafeCTimeAccessTest.test_getGmtimeAtTheEpoch "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/SafeTimeAccessTest" "--gtest_filter=SafeCTimeAccessTest.test_getGmtimeAtTheEpoch")
add_test(SafeCTimeAccessTest.test_getGmtime "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/SafeTimeAccessTest" "--gtest_filter=SafeCTimeAccessTest.test_getGmtime")
add_test(SafeCTimeAccessTest.test_getLocaltime "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/SafeTimeAccessTest" "--gtest_filter=SafeCTimeAccessTest.test_getLocaltime")
add_test(SafeCTimeAccessTest.test_gmTimeMultithreadedAccess "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/SafeTimeAccessTest" "--gtest_also_run_disabled_tests" "--gtest_filter=SafeCTimeAccessTest.DISABLED_test_gmTimeMultithreadedAccess")
set_tests_properties(SafeCTimeAccessTest.test_gmTimeMultithreadedAccess PROPERTIES  DISABLED "TRUE")
add_test(SafeCTimeAccessTest.test_localtimeMultithreadedAccess "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/SafeTimeAccessTest" "--gtest_also_run_disabled_tests" "--gtest_filter=SafeCTimeAccessTest.DISABLED_test_localtimeMultithreadedAccess")
set_tests_properties(SafeCTimeAccessTest.test_localtimeMultithreadedAccess PROPERTIES  DISABLED "TRUE")
add_test(SharedDataStreamTest.test_sdsCalculateCreateSize "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/SharedDataStreamTest" "--gtest_filter=SharedDataStreamTest.test_sdsCalculateCreateSize")
add_test(SharedDataStreamTest.test_sdsOpen "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/SharedDataStreamTest" "--gtest_filter=SharedDataStreamTest.test_sdsOpen")
add_test(SharedDataStreamTest.test_createWriter "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/SharedDataStreamTest" "--gtest_filter=SharedDataStreamTest.test_createWriter")
add_test(SharedDataStreamTest.test_createReader "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/SharedDataStreamTest" "--gtest_filter=SharedDataStreamTest.test_createReader")
add_test(SharedDataStreamTest.test_createReaderWhileWriting "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/SharedDataStreamTest" "--gtest_filter=SharedDataStreamTest.test_createReaderWhileWriting")
add_test(SharedDataStreamTest.test_readerRead "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/SharedDataStreamTest" "--gtest_also_run_disabled_tests" "--gtest_filter=SharedDataStreamTest.DISABLED_test_readerRead")
set_tests_properties(SharedDataStreamTest.test_readerRead PROPERTIES  DISABLED "TRUE")
add_test(SharedDataStreamTest.test_readerSeek "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/SharedDataStreamTest" "--gtest_filter=SharedDataStreamTest.test_readerSeek")
add_test(SharedDataStreamTest.test_readerTell "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/SharedDataStreamTest" "--gtest_filter=SharedDataStreamTest.test_readerTell")
add_test(SharedDataStreamTest.test_readerClose "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/SharedDataStreamTest" "--gtest_filter=SharedDataStreamTest.test_readerClose")
add_test(SharedDataStreamTest.test_readerGetId "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/SharedDataStreamTest" "--gtest_filter=SharedDataStreamTest.test_readerGetId")
add_test(SharedDataStreamTest.test_readerGetWordSize "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/SharedDataStreamTest" "--gtest_filter=SharedDataStreamTest.test_readerGetWordSize")
add_test(SharedDataStreamTest.test_writerWrite "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/SharedDataStreamTest" "--gtest_filter=SharedDataStreamTest.test_writerWrite")
add_test(SharedDataStreamTest.test_writerTell "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/SharedDataStreamTest" "--gtest_filter=SharedDataStreamTest.test_writerTell")
add_test(SharedDataStreamTest.test_writerClose "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/SharedDataStreamTest" "--gtest_filter=SharedDataStreamTest.test_writerClose")
add_test(SharedDataStreamTest.test_writerGetWordSize "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/SharedDataStreamTest" "--gtest_filter=SharedDataStreamTest.test_writerGetWordSize")
add_test(SharedDataStreamTest.testTimer_concurrencyNonblockableWriterDualReader "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/SharedDataStreamTest" "--gtest_also_run_disabled_tests" "--gtest_filter=SharedDataStreamTest.DISABLED_testTimer_concurrencyNonblockableWriterDualReader")
set_tests_properties(SharedDataStreamTest.testTimer_concurrencyNonblockableWriterDualReader PROPERTIES  DISABLED "TRUE" LABELS "timertest")
add_test(SharedDataStreamTest.test_concurrencyAllOrNothingWriterNonblockingReader "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/SharedDataStreamTest" "--gtest_filter=SharedDataStreamTest.test_concurrencyAllOrNothingWriterNonblockingReader")
add_test(SharedDataStreamTest.test_concurrencyMultipleSds "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/SharedDataStreamTest" "--gtest_filter=SharedDataStreamTest.test_concurrencyMultipleSds")
add_test(SharedDataStreamTest.test_writerClosedBeforeWriting "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/SharedDataStreamTest" "--gtest_filter=SharedDataStreamTest.test_writerClosedBeforeWriting")
add_test(SharedDataStreamTest.test_writerClosedBeforeAttachingReader "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/SharedDataStreamTest" "--gtest_filter=SharedDataStreamTest.test_writerClosedBeforeAttachingReader")
add_test(StopwatchTest.test_goodSequencing "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/StopwatchTest" "--gtest_filter=StopwatchTest.test_goodSequencing")
add_test(StopwatchTest.test_badSequencing "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/StopwatchTest" "--gtest_filter=StopwatchTest.test_badSequencing")
add_test(StopwatchTest.testSlow_elapsed "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/StopwatchTest" "--gtest_filter=StopwatchTest.testSlow_elapsed")
set_tests_properties(StopwatchTest.testSlow_elapsed PROPERTIES  LABELS "slowtest")
add_test(StreamFunctionsTest.test_streamFromData "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/StreamFunctionsTest" "--gtest_filter=StreamFunctionsTest.test_streamFromData")
add_test(StreamFunctionsTest.test_dataContainsUnprintableChars "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/StreamFunctionsTest" "--gtest_filter=StreamFunctionsTest.test_dataContainsUnprintableChars")
add_test(StreamFunctionsTest.test_emptyVector "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/StreamFunctionsTest" "--gtest_filter=StreamFunctionsTest.test_emptyVector")
add_test(StreamFunctionsTest.test_multipleStreams "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/StreamFunctionsTest" "--gtest_filter=StreamFunctionsTest.test_multipleStreams")
add_test(StreamFunctionsTest.test_seekgBasicForward "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/StreamFunctionsTest" "--gtest_filter=StreamFunctionsTest.test_seekgBasicForward")
add_test(StreamFunctionsTest.test_seekgBasicReset "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/StreamFunctionsTest" "--gtest_filter=StreamFunctionsTest.test_seekgBasicReset")
add_test(StreamFunctionsTest.test_tellgBasic "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/StreamFunctionsTest" "--gtest_filter=StreamFunctionsTest.test_tellgBasic")
add_test(StreamFunctionsTest.test_tellgPastEnd "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/StreamFunctionsTest" "--gtest_filter=StreamFunctionsTest.test_tellgPastEnd")
add_test(StreamFunctionsTest.test_tellgBeforeBeginning "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/StreamFunctionsTest" "--gtest_filter=StreamFunctionsTest.test_tellgBeforeBeginning")
add_test(StreamFunctionsTest.test_tellgAfterSeeking "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/StreamFunctionsTest" "--gtest_filter=StreamFunctionsTest.test_tellgAfterSeeking")
add_test(StreamFunctionsTest.test_tellgAfterReading "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/StreamFunctionsTest" "--gtest_filter=StreamFunctionsTest.test_tellgAfterReading")
add_test(StreambufTest.test_creation "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/StreambufTest" "--gtest_filter=StreambufTest.test_creation")
add_test(StreambufTest.test_seekoffBeginning "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/StreambufTest" "--gtest_filter=StreambufTest.test_seekoffBeginning")
add_test(StreambufTest.test_seekoffCurrentForward "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/StreambufTest" "--gtest_filter=StreambufTest.test_seekoffCurrentForward")
add_test(StreambufTest.test_seekoffFromBeginningUntilEnd "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/StreambufTest" "--gtest_filter=StreambufTest.test_seekoffFromBeginningUntilEnd")
add_test(StreambufTest.test_seekoffFromEndUntilBeginning "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/StreambufTest" "--gtest_filter=StreambufTest.test_seekoffFromEndUntilBeginning")
add_test(StreambufTest.test_seekoffCurrentBackward "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/StreambufTest" "--gtest_filter=StreambufTest.test_seekoffCurrentBackward")
add_test(StreambufTest.test_seekoffBeforeStart "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/StreambufTest" "--gtest_filter=StreambufTest.test_seekoffBeforeStart")
add_test(StreambufTest.test_seekoffPastEnd "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/StreambufTest" "--gtest_filter=StreambufTest.test_seekoffPastEnd")
add_test(StreambufTest.test_seekpos "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/StreambufTest" "--gtest_filter=StreambufTest.test_seekpos")
add_test(StreambufTest.test_seekposBeforeStart "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/StreambufTest" "--gtest_filter=StreambufTest.test_seekposBeforeStart")
add_test(StreambufTest.test_seekposAfterEnd "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/StreambufTest" "--gtest_filter=StreambufTest.test_seekposAfterEnd")
add_test(StreambufTest.test_seekposToEnd "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/StreambufTest" "--gtest_filter=StreambufTest.test_seekposToEnd")
add_test(StringUtilsTest.test_emptyStringFails "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/StringUtilsTest" "--gtest_filter=StringUtilsTest.test_emptyStringFails")
add_test(StringUtilsTest.test_simpleDecimalInteger "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/StringUtilsTest" "--gtest_filter=StringUtilsTest.test_simpleDecimalInteger")
add_test(StringUtilsTest.test_negativeInt "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/StringUtilsTest" "--gtest_filter=StringUtilsTest.test_negativeInt")
add_test(StringUtilsTest.test_initialWhitespaceSucceeds "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/StringUtilsTest" "--gtest_filter=StringUtilsTest.test_initialWhitespaceSucceeds")
add_test(StringUtilsTest.test_trailingWhitespaceSucceeds "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/StringUtilsTest" "--gtest_filter=StringUtilsTest.test_trailingWhitespaceSucceeds")
add_test(StringUtilsTest.test_leadingAndTrailingWhitespaceSucceeds "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/StringUtilsTest" "--gtest_filter=StringUtilsTest.test_leadingAndTrailingWhitespaceSucceeds")
add_test(StringUtilsTest.test_nonWhitespacePrefixFails "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/StringUtilsTest" "--gtest_filter=StringUtilsTest.test_nonWhitespacePrefixFails")
add_test(StringUtilsTest.test_nonWhitespaceSuffixFails "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/StringUtilsTest" "--gtest_filter=StringUtilsTest.test_nonWhitespaceSuffixFails")
add_test(StringUtilsTest.test_nonWhitespacePrefixAndSuffixFails "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/StringUtilsTest" "--gtest_filter=StringUtilsTest.test_nonWhitespacePrefixAndSuffixFails")
add_test(StringUtilsTest.test_nonWhitespaceAndNonWhitespacePrefixFails "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/StringUtilsTest" "--gtest_filter=StringUtilsTest.test_nonWhitespaceAndNonWhitespacePrefixFails")
add_test(StringUtilsTest.test_nonWhitespaceAndNonWhitespaceSuffixFails "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/StringUtilsTest" "--gtest_filter=StringUtilsTest.test_nonWhitespaceAndNonWhitespaceSuffixFails")
add_test(StringUtilsTest.test_nonWhitespaceAndNonWhitespacePrefixAndSuffixFails "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/StringUtilsTest" "--gtest_filter=StringUtilsTest.test_nonWhitespaceAndNonWhitespacePrefixAndSuffixFails")
add_test(StringUtilsTest.test_zeroSucceeds "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/StringUtilsTest" "--gtest_filter=StringUtilsTest.test_zeroSucceeds")
add_test(StringUtilsTest.test_decimalFloatFails "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/StringUtilsTest" "--gtest_filter=StringUtilsTest.test_decimalFloatFails")
add_test(StringUtilsTest.test_octalInterpretedAsDecimal "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/StringUtilsTest" "--gtest_filter=StringUtilsTest.test_octalInterpretedAsDecimal")
add_test(StringUtilsTest.test_hexIntFails "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/StringUtilsTest" "--gtest_filter=StringUtilsTest.test_hexIntFails")
add_test(StringUtilsTest.test_tooLargeIntFails "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/StringUtilsTest" "--gtest_filter=StringUtilsTest.test_tooLargeIntFails")
add_test(StringUtilsTest.test_tooSmallIntFails "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/StringUtilsTest" "--gtest_filter=StringUtilsTest.test_tooSmallIntFails")
add_test(StringUtilsTest.test_multipleNumbers "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/StringUtilsTest" "--gtest_filter=StringUtilsTest.test_multipleNumbers")
add_test(StringUtilsTest.test_toLowerEmptyString "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/StringUtilsTest" "--gtest_filter=StringUtilsTest.test_toLowerEmptyString")
add_test(StringUtilsTest.test_toLowerCaseString "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/StringUtilsTest" "--gtest_filter=StringUtilsTest.test_toLowerCaseString")
add_test(StringUtilsTest.test_toUpperCaseString "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/StringUtilsTest" "--gtest_filter=StringUtilsTest.test_toUpperCaseString")
add_test(StringUtilsTest.test_toCamelCaseString "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/StringUtilsTest" "--gtest_filter=StringUtilsTest.test_toCamelCaseString")
add_test(TaskThreadTest.test_waitForNothing "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/TaskThreadTest" "--gtest_filter=TaskThreadTest.test_waitForNothing")
add_test(TaskThreadTest.test_startFailsDueToEmptyFunction "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/TaskThreadTest" "--gtest_filter=TaskThreadTest.test_startFailsDueToEmptyFunction")
add_test(TaskThreadTest.test_simpleJob "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/TaskThreadTest" "--gtest_filter=TaskThreadTest.test_simpleJob")
add_test(TaskThreadTest.test_sequenceJobs "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/TaskThreadTest" "--gtest_filter=TaskThreadTest.test_sequenceJobs")
add_test(TaskThreadTest.test_startNewJob "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/TaskThreadTest" "--gtest_filter=TaskThreadTest.test_startNewJob")
add_test(TaskThreadTest.testTimer_startFailDueTooManyThreads "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/TaskThreadTest" "--gtest_filter=TaskThreadTest.testTimer_startFailDueTooManyThreads")
set_tests_properties(TaskThreadTest.testTimer_startFailDueTooManyThreads PROPERTIES  LABELS "timertest")
add_test(TaskThreadTest.test_moniker "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/TaskThreadTest" "--gtest_also_run_disabled_tests" "--gtest_filter=TaskThreadTest.DISABLED_test_moniker")
set_tests_properties(TaskThreadTest.test_moniker PROPERTIES  DISABLED "TRUE")
add_test(TaskThreadTest.test_monikerDifferentObjects "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/TaskThreadTest" "--gtest_filter=TaskThreadTest.test_monikerDifferentObjects")
add_test(TaskThreadTest.test_obtainAndreleaseWorker "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/ThreadPoolTest" "--gtest_filter=TaskThreadTest.test_obtainAndreleaseWorker")
add_test(TaskThreadTest.test_releaseMultipleHonorsMax "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/ThreadPoolTest" "--gtest_filter=TaskThreadTest.test_releaseMultipleHonorsMax")
add_test(TimeTest.test_stringConversion "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/TimeUtilsTest" "--gtest_filter=TimeTest.test_stringConversion")
add_test(TimeTest.test_stringConversionError "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/TimeUtilsTest" "--gtest_filter=TimeTest.test_stringConversionError")
add_test(TimeTest.test_stringConversionNullParam "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/TimeUtilsTest" "--gtest_filter=TimeTest.test_stringConversionNullParam")
add_test(TimeTest.test_timeConversion "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/TimeUtilsTest" "--gtest_filter=TimeTest.test_timeConversion")
add_test(TimeTest.test_timeConversionCurrentTime "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/TimeUtilsTest" "--gtest_filter=TimeTest.test_timeConversionCurrentTime")
add_test(TimeTest.test_currentTime "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/TimeUtilsTest" "--gtest_filter=TimeTest.test_currentTime")
add_test(TimeTest.test_currentTimeNullParam "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/TimeUtilsTest" "--gtest_filter=TimeTest.test_currentTimeNullParam")
add_test(TimeTest.test_iso8601Conversion "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/TimeUtilsTest" "--gtest_filter=TimeTest.test_iso8601Conversion")
add_test(TimerTest.testTimer_singleShot "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/TimerTest" "--gtest_filter=TimerTest.testTimer_singleShot")
set_tests_properties(TimerTest.testTimer_singleShot PROPERTIES  LABELS "timertest")
add_test(TimerTest.testTimer_multiShot "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/TimerTest" "--gtest_filter=TimerTest.testTimer_multiShot")
set_tests_properties(TimerTest.testTimer_multiShot PROPERTIES  LABELS "timertest")
add_test(TimerTest.testTimer_multiShotWithDelay "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/TimerTest" "--gtest_filter=TimerTest.testTimer_multiShotWithDelay")
set_tests_properties(TimerTest.testTimer_multiShotWithDelay PROPERTIES  LABELS "timertest")
add_test(TimerTest.testTimer_forever "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/TimerTest" "--gtest_filter=TimerTest.testTimer_forever")
set_tests_properties(TimerTest.testTimer_forever PROPERTIES  LABELS "timertest")
add_test(TimerTest.testTimer_slowTaskLessThanPeriod "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/TimerTest" "--gtest_filter=TimerTest.testTimer_slowTaskLessThanPeriod")
set_tests_properties(TimerTest.testTimer_slowTaskLessThanPeriod PROPERTIES  LABELS "timertest")
add_test(TimerTest.testTimer_slowTaskGreaterThanPeriod "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/TimerTest" "--gtest_filter=TimerTest.testTimer_slowTaskGreaterThanPeriod")
set_tests_properties(TimerTest.testTimer_slowTaskGreaterThanPeriod PROPERTIES  LABELS "timertest")
add_test(TimerTest.testTimer_slowTaskGreaterThanTwoPeriods "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/TimerTest" "--gtest_filter=TimerTest.testTimer_slowTaskGreaterThanTwoPeriods")
set_tests_properties(TimerTest.testTimer_slowTaskGreaterThanTwoPeriods PROPERTIES  LABELS "timertest")
add_test(TimerTest.testTimer_endToStartPeriod "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/TimerTest" "--gtest_filter=TimerTest.testTimer_endToStartPeriod")
set_tests_properties(TimerTest.testTimer_endToStartPeriod PROPERTIES  LABELS "timertest")
add_test(TimerTest.testTimer_stopSingleShotBeforeTask "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/TimerTest" "--gtest_filter=TimerTest.testTimer_stopSingleShotBeforeTask")
set_tests_properties(TimerTest.testTimer_stopSingleShotBeforeTask PROPERTIES  LABELS "timertest")
add_test(TimerTest.testTimer_stopSingleShotDuringTask "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/TimerTest" "--gtest_filter=TimerTest.testTimer_stopSingleShotDuringTask")
set_tests_properties(TimerTest.testTimer_stopSingleShotDuringTask PROPERTIES  LABELS "timertest")
add_test(TimerTest.testTimer_stopSingleShotAfterTask "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/TimerTest" "--gtest_filter=TimerTest.testTimer_stopSingleShotAfterTask")
set_tests_properties(TimerTest.testTimer_stopSingleShotAfterTask PROPERTIES  LABELS "timertest")
add_test(TimerTest.testTimer_stopMultiShot "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/TimerTest" "--gtest_filter=TimerTest.testTimer_stopMultiShot")
set_tests_properties(TimerTest.testTimer_stopMultiShot PROPERTIES  LABELS "timertest")
add_test(TimerTest.testTimer_startRunningBeforeTask "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/TimerTest" "--gtest_filter=TimerTest.testTimer_startRunningBeforeTask")
set_tests_properties(TimerTest.testTimer_startRunningBeforeTask PROPERTIES  LABELS "timertest")
add_test(TimerTest.testTimer_startRunningDuringTask "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/TimerTest" "--gtest_filter=TimerTest.testTimer_startRunningDuringTask")
set_tests_properties(TimerTest.testTimer_startRunningDuringTask PROPERTIES  LABELS "timertest")
add_test(TimerTest.testTimer_startRunningAfterTask "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/TimerTest" "--gtest_filter=TimerTest.testTimer_startRunningAfterTask")
set_tests_properties(TimerTest.testTimer_startRunningAfterTask PROPERTIES  LABELS "timertest")
add_test(TimerTest.test_deleteBeforeTask "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/TimerTest" "--gtest_filter=TimerTest.test_deleteBeforeTask")
add_test(TimerTest.testTimer_deleteDuringTask "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/TimerTest" "--gtest_filter=TimerTest.testTimer_deleteDuringTask")
set_tests_properties(TimerTest.testTimer_deleteDuringTask PROPERTIES  LABELS "timertest")
add_test(TimerTest.testTimer_startRunningAfterStopDuringTask "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/TimerTest" "--gtest_filter=TimerTest.testTimer_startRunningAfterStopDuringTask")
set_tests_properties(TimerTest.testTimer_startRunningAfterStopDuringTask PROPERTIES  LABELS "timertest")
add_test(TimerTest.testTimer_multipleStopsDoesntDeadlock "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/TimerTest" "--gtest_filter=TimerTest.testTimer_multipleStopsDoesntDeadlock")
set_tests_properties(TimerTest.testTimer_multipleStopsDoesntDeadlock PROPERTIES  LABELS "timertest")
add_test(UUIDGenerationTest.test_uUIDStringLength "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/UUIDGenerationTest" "--gtest_filter=UUIDGenerationTest.test_uUIDStringLength")
add_test(UUIDGenerationTest.test_uUIDContainsOnlyHexCharacters "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/UUIDGenerationTest" "--gtest_filter=UUIDGenerationTest.test_uUIDContainsOnlyHexCharacters")
add_test(UUIDGenerationTest.test_uUIDVersion "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/UUIDGenerationTest" "--gtest_filter=UUIDGenerationTest.test_uUIDVersion")
add_test(UUIDGenerationTest.test_uUIDVariant "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/UUIDGenerationTest" "--gtest_filter=UUIDGenerationTest.test_uUIDVariant")
add_test(UUIDGenerationTest.addSeedTest "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/UUIDGenerationTest" "--gtest_filter=UUIDGenerationTest.addSeedTest")
add_test(UUIDGenerationTest.test_multipleConcurrentSaltSettings "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/UUIDGenerationTest" "--gtest_filter=UUIDGenerationTest.test_multipleConcurrentSaltSettings")
add_test(UUIDGenerationTest.test_uUIDHyphens "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/UUIDGenerationTest" "--gtest_filter=UUIDGenerationTest.test_uUIDHyphens")
add_test(UUIDGenerationTest.test_multipleRequests "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/UUIDGenerationTest" "--gtest_filter=UUIDGenerationTest.test_multipleRequests")
add_test(UUIDGenerationTest.test_multipleConcurrentRequests "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/UUIDGenerationTest" "--gtest_filter=UUIDGenerationTest.test_multipleConcurrentRequests")
add_test(UUIDGenerationTest.test_allHexValuesGenerated "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/UUIDGenerationTest" "--gtest_filter=UUIDGenerationTest.test_allHexValuesGenerated")
add_test(TaskThreadTest.test_runWorkSeveralTimes "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/WorkerThreadTest" "--gtest_filter=TaskThreadTest.test_runWorkSeveralTimes")
add_test(TaskThreadTest.test_runWorkRepeatedlyAndFinish "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/WorkerThreadTest" "--gtest_filter=TaskThreadTest.test_runWorkRepeatedlyAndFinish")
add_test(TaskThreadTest.test_runWorkRepeatedlyAndCancelFromWorkerHappensImmediately "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/WorkerThreadTest" "--gtest_filter=TaskThreadTest.test_runWorkRepeatedlyAndCancelFromWorkerHappensImmediately")
add_test(TaskThreadTest.test_runWorkRepeatedlyAndCancel "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/WorkerThreadTest" "--gtest_filter=TaskThreadTest.test_runWorkRepeatedlyAndCancel")
add_test(TaskThreadTest.test_runWorkRepeatedlyWithCancelAndInterruptByDestruction "/home/pi/sdk-folder/sdk-build/AVSCommon/Utils/test/WorkerThreadTest" "--gtest_filter=TaskThreadTest.test_runWorkRepeatedlyWithCancelAndInterruptByDestruction")
subdirs("Common")
