# CMake generated Testfile for 
# Source directory: /home/pi/sdk-folder/sdk-source/avs-device-sdk/CapabilityAgents/SoftwareComponentReporter/test
# Build directory: /home/pi/sdk-folder/sdk-build/CapabilityAgents/SoftwareComponentReporter/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(SoftwareComponentReporterCapabilityAgentTest.test_addComponentConfiguration "/home/pi/sdk-folder/sdk-build/CapabilityAgents/SoftwareComponentReporter/test/SoftwareComponentReporterCapabilityAgentTest" "--gtest_filter=SoftwareComponentReporterCapabilityAgentTest.test_addComponentConfiguration")
add_test(SoftwareComponentReporterCapabilityAgentTest.test_addMultipleComponentConfiguration "/home/pi/sdk-folder/sdk-build/CapabilityAgents/SoftwareComponentReporter/test/SoftwareComponentReporterCapabilityAgentTest" "--gtest_filter=SoftwareComponentReporterCapabilityAgentTest.test_addMultipleComponentConfiguration")
add_test(SoftwareComponentReporterCapabilityAgentTest.test_addDupeComponentConfiguration "/home/pi/sdk-folder/sdk-build/CapabilityAgents/SoftwareComponentReporter/test/SoftwareComponentReporterCapabilityAgentTest" "--gtest_filter=SoftwareComponentReporterCapabilityAgentTest.test_addDupeComponentConfiguration")
add_test(SoftwareComponentReporterCapabilityAgentTest.test_configurationJsonBuilds "/home/pi/sdk-folder/sdk-build/CapabilityAgents/SoftwareComponentReporter/test/SoftwareComponentReporterCapabilityAgentTest" "--gtest_filter=SoftwareComponentReporterCapabilityAgentTest.test_configurationJsonBuilds")
add_test(SoftwareComponentReporterCapabilityAgentTest.test_configurationJsonEmpty "/home/pi/sdk-folder/sdk-build/CapabilityAgents/SoftwareComponentReporter/test/SoftwareComponentReporterCapabilityAgentTest" "--gtest_filter=SoftwareComponentReporterCapabilityAgentTest.test_configurationJsonEmpty")
