# CMake generated Testfile for 
# Source directory: /home/pi/sdk-folder/sdk-source/avs-device-sdk/ACL/test
# Build directory: /home/pi/sdk-folder/sdk-build/ACL/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(AVSConnectionManagerTest.test_create "/home/pi/sdk-folder/sdk-build/ACL/test/AVSConnectionManagerTest" "--gtest_filter=AVSConnectionManagerTest.test_create")
add_test(AVSConnectionManagerTest.test_createWithNullMessageRouterAndObservers "/home/pi/sdk-folder/sdk-build/ACL/test/AVSConnectionManagerTest" "--gtest_filter=AVSConnectionManagerTest.test_createWithNullMessageRouterAndObservers")
add_test(AVSConnectionManagerTest.test_addConnectionStatusObserverNull "/home/pi/sdk-folder/sdk-build/ACL/test/AVSConnectionManagerTest" "--gtest_filter=AVSConnectionManagerTest.test_addConnectionStatusObserverNull")
add_test(AVSConnectionManagerTest.test_addConnectionStatusObserverValid "/home/pi/sdk-folder/sdk-build/ACL/test/AVSConnectionManagerTest" "--gtest_filter=AVSConnectionManagerTest.test_addConnectionStatusObserverValid")
add_test(AVSConnectionManagerTest.test_removeConnectionStatusObserverNull "/home/pi/sdk-folder/sdk-build/ACL/test/AVSConnectionManagerTest" "--gtest_filter=AVSConnectionManagerTest.test_removeConnectionStatusObserverNull")
add_test(AVSConnectionManagerTest.test_addMessageObserverNull "/home/pi/sdk-folder/sdk-build/ACL/test/AVSConnectionManagerTest" "--gtest_filter=AVSConnectionManagerTest.test_addMessageObserverNull")
add_test(AVSConnectionManagerTest.test_removeMessageObserverNull "/home/pi/sdk-folder/sdk-build/ACL/test/AVSConnectionManagerTest" "--gtest_filter=AVSConnectionManagerTest.test_removeMessageObserverNull")
add_test(AVSConnectionManagerTest.test_enableAndDisableFunction "/home/pi/sdk-folder/sdk-build/ACL/test/AVSConnectionManagerTest" "--gtest_filter=AVSConnectionManagerTest.test_enableAndDisableFunction")
add_test(AVSConnectionManagerTest.test_sendMessageRequest "/home/pi/sdk-folder/sdk-build/ACL/test/AVSConnectionManagerTest" "--gtest_filter=AVSConnectionManagerTest.test_sendMessageRequest")
add_test(AVSConnectionManagerTest.test_setAVSGateway "/home/pi/sdk-folder/sdk-build/ACL/test/AVSConnectionManagerTest" "--gtest_filter=AVSConnectionManagerTest.test_setAVSGateway")
add_test(AVSConnectionManagerTest.getAVSGatewayTest "/home/pi/sdk-folder/sdk-build/ACL/test/AVSConnectionManagerTest" "--gtest_filter=AVSConnectionManagerTest.getAVSGatewayTest")
add_test(AVSConnectionManagerTest.test_enabledOnConnectStatusChangedToFalse "/home/pi/sdk-folder/sdk-build/ACL/test/AVSConnectionManagerTest" "--gtest_filter=AVSConnectionManagerTest.test_enabledOnConnectStatusChangedToFalse")
add_test(AVSConnectionManagerTest.test_enabledOnConnectStatusChangedToTrue "/home/pi/sdk-folder/sdk-build/ACL/test/AVSConnectionManagerTest" "--gtest_filter=AVSConnectionManagerTest.test_enabledOnConnectStatusChangedToTrue")
add_test(AVSConnectionManagerTest.test_disabledOnConnectStatusChanged "/home/pi/sdk-folder/sdk-build/ACL/test/AVSConnectionManagerTest" "--gtest_filter=AVSConnectionManagerTest.test_disabledOnConnectStatusChanged")
add_test(HTTP2TransportTest.testSlow_emptyAuthToken "/home/pi/sdk-folder/sdk-build/ACL/test/HTTP2TransportTest" "--gtest_filter=HTTP2TransportTest.testSlow_emptyAuthToken")
set_tests_properties(HTTP2TransportTest.testSlow_emptyAuthToken PROPERTIES  LABELS "slowtest")
add_test(HTTP2TransportTest.testSlow_waitAuthDelegateInterface "/home/pi/sdk-folder/sdk-build/ACL/test/HTTP2TransportTest" "--gtest_filter=HTTP2TransportTest.testSlow_waitAuthDelegateInterface")
set_tests_properties(HTTP2TransportTest.testSlow_waitAuthDelegateInterface PROPERTIES  LABELS "slowtest")
add_test(HTTP2TransportTest.test_bearerTokenInRequest "/home/pi/sdk-folder/sdk-build/ACL/test/HTTP2TransportTest" "--gtest_filter=HTTP2TransportTest.test_bearerTokenInRequest")
add_test(HTTP2TransportTest.test_triggerPostConnectObject "/home/pi/sdk-folder/sdk-build/ACL/test/HTTP2TransportTest" "--gtest_filter=HTTP2TransportTest.test_triggerPostConnectObject")
add_test(HTTP2TransportTest.test_connectionStatusOnPostConnect "/home/pi/sdk-folder/sdk-build/ACL/test/HTTP2TransportTest" "--gtest_filter=HTTP2TransportTest.test_connectionStatusOnPostConnect")
add_test(HTTP2TransportTest.testSlow_retryOnDownchannelConnectionFailure "/home/pi/sdk-folder/sdk-build/ACL/test/HTTP2TransportTest" "--gtest_filter=HTTP2TransportTest.testSlow_retryOnDownchannelConnectionFailure")
set_tests_properties(HTTP2TransportTest.testSlow_retryOnDownchannelConnectionFailure PROPERTIES  LABELS "slowtest")
add_test(HTTP2TransportTest.test_messageRequestContent "/home/pi/sdk-folder/sdk-build/ACL/test/HTTP2TransportTest" "--gtest_filter=HTTP2TransportTest.test_messageRequestContent")
add_test(HTTP2TransportTest.test_messageRequestWithAttachment "/home/pi/sdk-folder/sdk-build/ACL/test/HTTP2TransportTest" "--gtest_filter=HTTP2TransportTest.test_messageRequestWithAttachment")
add_test(HTTP2TransportTest.test_pauseSendWhenSDSEmpty "/home/pi/sdk-folder/sdk-build/ACL/test/HTTP2TransportTest" "--gtest_filter=HTTP2TransportTest.test_pauseSendWhenSDSEmpty")
add_test(HTTP2TransportTest.testSlow_messageRequestsQueuing "/home/pi/sdk-folder/sdk-build/ACL/test/HTTP2TransportTest" "--gtest_filter=HTTP2TransportTest.testSlow_messageRequestsQueuing")
set_tests_properties(HTTP2TransportTest.testSlow_messageRequestsQueuing PROPERTIES  LABELS "slowtest")
add_test(HTTP2TransportTest.messageRequests_SequentialSend "/home/pi/sdk-folder/sdk-build/ACL/test/HTTP2TransportTest" "--gtest_filter=HTTP2TransportTest.messageRequests_SequentialSend")
add_test(HTTP2TransportTest.messageRequests_concurrentSend "/home/pi/sdk-folder/sdk-build/ACL/test/HTTP2TransportTest" "--gtest_filter=HTTP2TransportTest.messageRequests_concurrentSend")
add_test(HTTP2TransportTest.test_onSendCompletedNotification "/home/pi/sdk-folder/sdk-build/ACL/test/HTTP2TransportTest" "--gtest_filter=HTTP2TransportTest.test_onSendCompletedNotification")
add_test(HTTP2TransportTest.test_onExceptionReceivedNon200Content "/home/pi/sdk-folder/sdk-build/ACL/test/HTTP2TransportTest" "--gtest_filter=HTTP2TransportTest.test_onExceptionReceivedNon200Content")
add_test(HTTP2TransportTest.test_messageConsumerReceiveDirective "/home/pi/sdk-folder/sdk-build/ACL/test/HTTP2TransportTest" "--gtest_filter=HTTP2TransportTest.test_messageConsumerReceiveDirective")
add_test(HTTP2TransportTest.test_onServerSideDisconnectOnDownchannelClosure "/home/pi/sdk-folder/sdk-build/ACL/test/HTTP2TransportTest" "--gtest_filter=HTTP2TransportTest.test_onServerSideDisconnectOnDownchannelClosure")
add_test(HTTP2TransportTest.test_messageRequestTimeoutPingRequest "/home/pi/sdk-folder/sdk-build/ACL/test/HTTP2TransportTest" "--gtest_filter=HTTP2TransportTest.test_messageRequestTimeoutPingRequest")
add_test(HTTP2TransportTest.testTimer_networkInactivityPingRequest "/home/pi/sdk-folder/sdk-build/ACL/test/HTTP2TransportTest" "--gtest_filter=HTTP2TransportTest.testTimer_networkInactivityPingRequest")
set_tests_properties(HTTP2TransportTest.testTimer_networkInactivityPingRequest PROPERTIES  LABELS "timertest")
add_test(HTTP2TransportTest.testSlow_tearDownPingTimeout "/home/pi/sdk-folder/sdk-build/ACL/test/HTTP2TransportTest" "--gtest_filter=HTTP2TransportTest.testSlow_tearDownPingTimeout")
set_tests_properties(HTTP2TransportTest.testSlow_tearDownPingTimeout PROPERTIES  LABELS "slowtest")
add_test(HTTP2TransportTest.testSlow_tearDownPingFailure "/home/pi/sdk-folder/sdk-build/ACL/test/HTTP2TransportTest" "--gtest_filter=HTTP2TransportTest.testSlow_tearDownPingFailure")
set_tests_properties(HTTP2TransportTest.testSlow_tearDownPingFailure PROPERTIES  LABELS "slowtest")
add_test(HTTP2TransportTest.testSlow_avsStreamsLimit "/home/pi/sdk-folder/sdk-build/ACL/test/HTTP2TransportTest" "--gtest_filter=HTTP2TransportTest.testSlow_avsStreamsLimit")
set_tests_properties(HTTP2TransportTest.testSlow_avsStreamsLimit PROPERTIES  LABELS "slowtest")
add_test(HTTP2TransportTest.test_onPostConnectFailureInitiatesShutdownAndNotifiesObservers "/home/pi/sdk-folder/sdk-build/ACL/test/HTTP2TransportTest" "--gtest_filter=HTTP2TransportTest.test_onPostConnectFailureInitiatesShutdownAndNotifiesObservers")
add_test(HTTP2TransportTest.test_eventTracerIsNotifiedForMessagesSent "/home/pi/sdk-folder/sdk-build/ACL/test/HTTP2TransportTest" "--gtest_filter=HTTP2TransportTest.test_eventTracerIsNotifiedForMessagesSent")
add_test(HTTP2TransportTest.test_eventTracerIsNotNotifiedForFailedMessages "/home/pi/sdk-folder/sdk-build/ACL/test/HTTP2TransportTest" "--gtest_filter=HTTP2TransportTest.test_eventTracerIsNotNotifiedForFailedMessages")
add_test(HTTP2TransportTest.test_eventTracerNotifiedForEmptyMessageContent "/home/pi/sdk-folder/sdk-build/ACL/test/HTTP2TransportTest" "--gtest_filter=HTTP2TransportTest.test_eventTracerNotifiedForEmptyMessageContent")
add_test(HTTP2TransportTest.test_eventTracerIsNotifiedForMultipleMessages "/home/pi/sdk-folder/sdk-build/ACL/test/HTTP2TransportTest" "--gtest_filter=HTTP2TransportTest.test_eventTracerIsNotifiedForMultipleMessages")
add_test(MessageRequestHandlerTest.test_headers "/home/pi/sdk-folder/sdk-build/ACL/test/MessageRequestHandlerTest" "--gtest_filter=MessageRequestHandlerTest.test_headers")
add_test(MessageRouterTest.test_getConnectionStatusReturnsDisconnectedBeforeConnect "/home/pi/sdk-folder/sdk-build/ACL/test/MessageRouterTest" "--gtest_filter=MessageRouterTest.test_getConnectionStatusReturnsDisconnectedBeforeConnect")
add_test(MessageRouterTest.test_getConnectionStatusReturnsPendingAfterConnectingStarts "/home/pi/sdk-folder/sdk-build/ACL/test/MessageRouterTest" "--gtest_filter=MessageRouterTest.test_getConnectionStatusReturnsPendingAfterConnectingStarts")
add_test(MessageRouterTest.test_getConnectionStatusReturnsConnectedAfterConnectionEstablished "/home/pi/sdk-folder/sdk-build/ACL/test/MessageRouterTest" "--gtest_filter=MessageRouterTest.test_getConnectionStatusReturnsConnectedAfterConnectionEstablished")
add_test(MessageRouterTest.test_getConnectionStatusReturnsConnectedAfterDisconnected "/home/pi/sdk-folder/sdk-build/ACL/test/MessageRouterTest" "--gtest_filter=MessageRouterTest.test_getConnectionStatusReturnsConnectedAfterDisconnected")
add_test(MessageRouterTest.test_ensureTheMessageRouterObserverIsInformedOfConnectionPendingAfterConnect "/home/pi/sdk-folder/sdk-build/ACL/test/MessageRouterTest" "--gtest_filter=MessageRouterTest.test_ensureTheMessageRouterObserverIsInformedOfConnectionPendingAfterConnect")
add_test(MessageRouterTest.test_ensureTheMessageRouterObserverIsInformedOfNewConnection "/home/pi/sdk-folder/sdk-build/ACL/test/MessageRouterTest" "--gtest_filter=MessageRouterTest.test_ensureTheMessageRouterObserverIsInformedOfNewConnection")
add_test(MessageRouterTest.test_ensureTheMessageRouterObserverIsInformedOfTransportDisconnection "/home/pi/sdk-folder/sdk-build/ACL/test/MessageRouterTest" "--gtest_filter=MessageRouterTest.test_ensureTheMessageRouterObserverIsInformedOfTransportDisconnection")
add_test(MessageRouterTest.test_ensureTheMessageRouterObserverIsInformedOfRouterDisconnection "/home/pi/sdk-folder/sdk-build/ACL/test/MessageRouterTest" "--gtest_filter=MessageRouterTest.test_ensureTheMessageRouterObserverIsInformedOfRouterDisconnection")
add_test(MessageRouterTest.test_sendIsSuccessfulWhenConnected "/home/pi/sdk-folder/sdk-build/ACL/test/MessageRouterTest" "--gtest_filter=MessageRouterTest.test_sendIsSuccessfulWhenConnected")
add_test(MessageRouterTest.test_sendFailsWhenDisconnected "/home/pi/sdk-folder/sdk-build/ACL/test/MessageRouterTest" "--gtest_filter=MessageRouterTest.test_sendFailsWhenDisconnected")
add_test(MessageRouterTest.test_sendFailsWhenPending "/home/pi/sdk-folder/sdk-build/ACL/test/MessageRouterTest" "--gtest_filter=MessageRouterTest.test_sendFailsWhenPending")
add_test(MessageRouterTest.test_sendMessageDoesNotSendAfterDisconnected "/home/pi/sdk-folder/sdk-build/ACL/test/MessageRouterTest" "--gtest_filter=MessageRouterTest.test_sendMessageDoesNotSendAfterDisconnected")
add_test(MessageRouterTest.test_disconnectDisconnectsConnectedTransports "/home/pi/sdk-folder/sdk-build/ACL/test/MessageRouterTest" "--gtest_filter=MessageRouterTest.test_disconnectDisconnectsConnectedTransports")
add_test(MessageRouterTest.test_serverSideDisconnectCreatesANewTransport "/home/pi/sdk-folder/sdk-build/ACL/test/MessageRouterTest" "--gtest_filter=MessageRouterTest.test_serverSideDisconnectCreatesANewTransport")
add_test(MessageRouterTest.test_onReceive "/home/pi/sdk-folder/sdk-build/ACL/test/MessageRouterTest" "--gtest_filter=MessageRouterTest.test_onReceive")
add_test(MessageRouterTest.test_onConnectionStatusChanged "/home/pi/sdk-folder/sdk-build/ACL/test/MessageRouterTest" "--gtest_filter=MessageRouterTest.test_onConnectionStatusChanged")
add_test(MessageRouterTest.test_enableTwiceOnPendingTransport "/home/pi/sdk-folder/sdk-build/ACL/test/MessageRouterTest" "--gtest_filter=MessageRouterTest.test_enableTwiceOnPendingTransport")
add_test(MessageRouterTest.test_onConnectedOnInactiveTransport "/home/pi/sdk-folder/sdk-build/ACL/test/MessageRouterTest" "--gtest_filter=MessageRouterTest.test_onConnectedOnInactiveTransport")
add_test(MessageRouterTest.setAndGetAVSGateway "/home/pi/sdk-folder/sdk-build/ACL/test/MessageRouterTest" "--gtest_filter=MessageRouterTest.setAndGetAVSGateway")
add_test(PostConnectSequencerFactoryTest.test_createWithNullProviders "/home/pi/sdk-folder/sdk-build/ACL/test/PostConnectSequencerFactoryTest" "--gtest_filter=PostConnectSequencerFactoryTest.test_createWithNullProviders")
add_test(PostConnectSequencerFactoryTest.test_createPostConnectCallsProviders "/home/pi/sdk-folder/sdk-build/ACL/test/PostConnectSequencerFactoryTest" "--gtest_filter=PostConnectSequencerFactoryTest.test_createPostConnectCallsProviders")
add_test(PostConnectSequencerFactoryTest.test_createPostConnectWhenProviderReturnsNull "/home/pi/sdk-folder/sdk-build/ACL/test/PostConnectSequencerFactoryTest" "--gtest_filter=PostConnectSequencerFactoryTest.test_createPostConnectWhenProviderReturnsNull")
add_test(PostConnectSequencerTest.test_postConnectOperationsSet "/home/pi/sdk-folder/sdk-build/ACL/test/PostConnectSequencerTest" "--gtest_filter=PostConnectSequencerTest.test_postConnectOperationsSet")
add_test(PostConnectSequencerTest.test_postConnectOperationsSetRemovesDuplicates "/home/pi/sdk-folder/sdk-build/ACL/test/PostConnectSequencerTest" "--gtest_filter=PostConnectSequencerTest.test_postConnectOperationsSetRemovesDuplicates")
add_test(PostConnectSequencerTest.test_happyPathAndPostConnectObserverGetsNotified "/home/pi/sdk-folder/sdk-build/ACL/test/PostConnectSequencerTest" "--gtest_filter=PostConnectSequencerTest.test_happyPathAndPostConnectObserverGetsNotified")
add_test(PostConnectSequencerTest.test_doPostConnectReturnFalseOnSecondCall "/home/pi/sdk-folder/sdk-build/ACL/test/PostConnectSequencerTest" "--gtest_filter=PostConnectSequencerTest.test_doPostConnectReturnFalseOnSecondCall")
add_test(PostConnectSequencerTest.test_subsequentOperationsDontExecute "/home/pi/sdk-folder/sdk-build/ACL/test/PostConnectSequencerTest" "--gtest_filter=PostConnectSequencerTest.test_subsequentOperationsDontExecute")
add_test(PostConnectSequencerTest.test_onDisconnectStopsExecution "/home/pi/sdk-folder/sdk-build/ACL/test/PostConnectSequencerTest" "--gtest_filter=PostConnectSequencerTest.test_onDisconnectStopsExecution")
subdirs("Transport")
